// Generated by tools/generate_desktop_bridge.py. Do not edit.
#include "QulQmlBridge.h"

#include "AlertData.h"
#include "ClusterInput.h"
#include "NavigationData.h"
#include "PhoneData.h"
#include "PhoneListData.h"
#include "Simulator.h"
#include "SystemData.h"
#include "TripData.h"
#include "VehicleData.h"

AlertDataQml::AlertDataQml(QObject *parent)
    : QObject(parent)
{
    AlertData &d = AlertData::instance();
    d.kind.setOnChanged([this] { emit kindChanged(); });
    d.level.setOnChanged([this] { emit levelChanged(); });
    d.popupVisible.setOnChanged([this] { emit popupVisibleChanged(); });
    d.phase.setOnChanged([this] { emit phaseChanged(); });
    d.sosSecondsLeft.setOnChanged([this] { emit sosSecondsLeftChanged(); });
    d.sosSent.setOnChanged([this] { emit sosSentChanged(); });
    d.protocolIndex.setOnChanged([this] { emit protocolIndexChanged(); });
    d.activeProtocol.setOnChanged([this] { emit activeProtocolChanged(); });
}

int AlertDataQml::kind() const
{
    return AlertData::instance().kind.value();
}

void AlertDataQml::qmlWriteKind(int value)
{
    AlertData::instance().kind.setValue(value);
}

int AlertDataQml::level() const
{
    return AlertData::instance().level.value();
}

void AlertDataQml::qmlWriteLevel(int value)
{
    AlertData::instance().level.setValue(value);
}

bool AlertDataQml::popupVisible() const
{
    return AlertData::instance().popupVisible.value();
}

void AlertDataQml::qmlWritePopupVisible(bool value)
{
    AlertData::instance().popupVisible.setValue(value);
}

int AlertDataQml::phase() const
{
    return AlertData::instance().phase.value();
}

void AlertDataQml::qmlWritePhase(int value)
{
    AlertData::instance().phase.setValue(value);
}

int AlertDataQml::sosSecondsLeft() const
{
    return AlertData::instance().sosSecondsLeft.value();
}

void AlertDataQml::qmlWriteSosSecondsLeft(int value)
{
    AlertData::instance().sosSecondsLeft.setValue(value);
}

bool AlertDataQml::sosSent() const
{
    return AlertData::instance().sosSent.value();
}

void AlertDataQml::qmlWriteSosSent(bool value)
{
    AlertData::instance().sosSent.setValue(value);
}

int AlertDataQml::protocolIndex() const
{
    return AlertData::instance().protocolIndex.value();
}

void AlertDataQml::qmlWriteProtocolIndex(int value)
{
    AlertData::instance().protocolIndex.setValue(value);
}

int AlertDataQml::activeProtocol() const
{
    return AlertData::instance().activeProtocol.value();
}

void AlertDataQml::qmlWriteActiveProtocol(int value)
{
    AlertData::instance().activeProtocol.setValue(value);
}

void AlertDataQml::acknowledge()
{
    AlertData::instance().acknowledge();
}

void AlertDataQml::update(int newKind, int newLevel)
{
    AlertData::instance().update(newKind, newLevel);
}

void AlertDataQml::tickSecond()
{
    AlertData::instance().tickSecond();
}

void AlertDataQml::cancelSos()
{
    AlertData::instance().cancelSos();
}

void AlertDataQml::activateProtocol()
{
    AlertData::instance().activateProtocol();
}

ClusterInputQml::ClusterInputQml(QObject *parent)
    : QObject(parent)
{
    ClusterInput &d = ClusterInput::instance();
    d.buttonEvent.connect([this](int button, int action) { emit buttonEvent(button, action); });
}

void ClusterInputQml::inject(int button, int action)
{
    ClusterInput::instance().inject(button, action);
}

NavigationDataQml::NavigationDataQml(QObject *parent)
    : QObject(parent)
{
    NavigationData &d = NavigationData::instance();
    d.active.setOnChanged([this] { emit activeChanged(); });
    d.maneuver.setOnChanged([this] { emit maneuverChanged(); });
    d.roundaboutExit.setOnChanged([this] { emit roundaboutExitChanged(); });
    d.distanceToManeuverM.setOnChanged([this] { emit distanceToManeuverMChanged(); });
    d.distanceRemainingM.setOnChanged([this] { emit distanceRemainingMChanged(); });
    d.etaMinutes.setOnChanged([this] { emit etaMinutesChanged(); });
    d.laneMask.setOnChanged([this] { emit laneMaskChanged(); });
    d.recommendedLaneMask.setOnChanged([this] { emit recommendedLaneMaskChanged(); });
    d.roadName.setOnChanged([this] { emit roadNameChanged(); });
}

bool NavigationDataQml::active() const
{
    return NavigationData::instance().active.value();
}

void NavigationDataQml::qmlWriteActive(bool value)
{
    NavigationData::instance().active.setValue(value);
}

int NavigationDataQml::maneuver() const
{
    return NavigationData::instance().maneuver.value();
}

void NavigationDataQml::qmlWriteManeuver(int value)
{
    NavigationData::instance().maneuver.setValue(value);
}

int NavigationDataQml::roundaboutExit() const
{
    return NavigationData::instance().roundaboutExit.value();
}

void NavigationDataQml::qmlWriteRoundaboutExit(int value)
{
    NavigationData::instance().roundaboutExit.setValue(value);
}

int NavigationDataQml::distanceToManeuverM() const
{
    return NavigationData::instance().distanceToManeuverM.value();
}

void NavigationDataQml::qmlWriteDistanceToManeuverM(int value)
{
    NavigationData::instance().distanceToManeuverM.setValue(value);
}

int NavigationDataQml::distanceRemainingM() const
{
    return NavigationData::instance().distanceRemainingM.value();
}

void NavigationDataQml::qmlWriteDistanceRemainingM(int value)
{
    NavigationData::instance().distanceRemainingM.setValue(value);
}

int NavigationDataQml::etaMinutes() const
{
    return NavigationData::instance().etaMinutes.value();
}

void NavigationDataQml::qmlWriteEtaMinutes(int value)
{
    NavigationData::instance().etaMinutes.setValue(value);
}

int NavigationDataQml::laneMask() const
{
    return NavigationData::instance().laneMask.value();
}

void NavigationDataQml::qmlWriteLaneMask(int value)
{
    NavigationData::instance().laneMask.setValue(value);
}

int NavigationDataQml::recommendedLaneMask() const
{
    return NavigationData::instance().recommendedLaneMask.value();
}

void NavigationDataQml::qmlWriteRecommendedLaneMask(int value)
{
    NavigationData::instance().recommendedLaneMask.setValue(value);
}

QString NavigationDataQml::roadName() const
{
    return QString::fromStdString(NavigationData::instance().roadName.value());
}

void NavigationDataQml::qmlWriteRoadName(const QString &value)
{
    NavigationData::instance().roadName.setValue(value.toStdString());
}

void NavigationDataQml::clear()
{
    NavigationData::instance().clear();
}

PhoneDataQml::PhoneDataQml(QObject *parent)
    : QObject(parent)
{
    PhoneData &d = PhoneData::instance();
    d.connected.setOnChanged([this] { emit connectedChanged(); });
    d.batteryPercent.setOnChanged([this] { emit batteryPercentChanged(); });
    d.signalBars.setOnChanged([this] { emit signalBarsChanged(); });
    d.internet.setOnChanged([this] { emit internetChanged(); });
    d.callStatus.setOnChanged([this] { emit callStatusChanged(); });
    d.callerName.setOnChanged([this] { emit callerNameChanged(); });
    d.mediaPlaying.setOnChanged([this] { emit mediaPlayingChanged(); });
    d.volume.setOnChanged([this] { emit volumeChanged(); });
    d.trackPositionS.setOnChanged([this] { emit trackPositionSChanged(); });
    d.trackDurationS.setOnChanged([this] { emit trackDurationSChanged(); });
    d.trackTitle.setOnChanged([this] { emit trackTitleChanged(); });
    d.trackArtist.setOnChanged([this] { emit trackArtistChanged(); });
    d.notificationSeq.setOnChanged([this] { emit notificationSeqChanged(); });
    d.notificationSender.setOnChanged([this] { emit notificationSenderChanged(); });
    d.notificationText.setOnChanged([this] { emit notificationTextChanged(); });
}

bool PhoneDataQml::connected() const
{
    return PhoneData::instance().connected.value();
}

void PhoneDataQml::qmlWriteConnected(bool value)
{
    PhoneData::instance().connected.setValue(value);
}

int PhoneDataQml::batteryPercent() const
{
    return PhoneData::instance().batteryPercent.value();
}

void PhoneDataQml::qmlWriteBatteryPercent(int value)
{
    PhoneData::instance().batteryPercent.setValue(value);
}

int PhoneDataQml::signalBars() const
{
    return PhoneData::instance().signalBars.value();
}

void PhoneDataQml::qmlWriteSignalBars(int value)
{
    PhoneData::instance().signalBars.setValue(value);
}

bool PhoneDataQml::internet() const
{
    return PhoneData::instance().internet.value();
}

void PhoneDataQml::qmlWriteInternet(bool value)
{
    PhoneData::instance().internet.setValue(value);
}

int PhoneDataQml::callStatus() const
{
    return PhoneData::instance().callStatus.value();
}

void PhoneDataQml::qmlWriteCallStatus(int value)
{
    PhoneData::instance().callStatus.setValue(value);
}

QString PhoneDataQml::callerName() const
{
    return QString::fromStdString(PhoneData::instance().callerName.value());
}

void PhoneDataQml::qmlWriteCallerName(const QString &value)
{
    PhoneData::instance().callerName.setValue(value.toStdString());
}

bool PhoneDataQml::mediaPlaying() const
{
    return PhoneData::instance().mediaPlaying.value();
}

void PhoneDataQml::qmlWriteMediaPlaying(bool value)
{
    PhoneData::instance().mediaPlaying.setValue(value);
}

int PhoneDataQml::volume() const
{
    return PhoneData::instance().volume.value();
}

void PhoneDataQml::qmlWriteVolume(int value)
{
    PhoneData::instance().volume.setValue(value);
}

int PhoneDataQml::trackPositionS() const
{
    return PhoneData::instance().trackPositionS.value();
}

void PhoneDataQml::qmlWriteTrackPositionS(int value)
{
    PhoneData::instance().trackPositionS.setValue(value);
}

int PhoneDataQml::trackDurationS() const
{
    return PhoneData::instance().trackDurationS.value();
}

void PhoneDataQml::qmlWriteTrackDurationS(int value)
{
    PhoneData::instance().trackDurationS.setValue(value);
}

QString PhoneDataQml::trackTitle() const
{
    return QString::fromStdString(PhoneData::instance().trackTitle.value());
}

void PhoneDataQml::qmlWriteTrackTitle(const QString &value)
{
    PhoneData::instance().trackTitle.setValue(value.toStdString());
}

QString PhoneDataQml::trackArtist() const
{
    return QString::fromStdString(PhoneData::instance().trackArtist.value());
}

void PhoneDataQml::qmlWriteTrackArtist(const QString &value)
{
    PhoneData::instance().trackArtist.setValue(value.toStdString());
}

int PhoneDataQml::notificationSeq() const
{
    return PhoneData::instance().notificationSeq.value();
}

void PhoneDataQml::qmlWriteNotificationSeq(int value)
{
    PhoneData::instance().notificationSeq.setValue(value);
}

QString PhoneDataQml::notificationSender() const
{
    return QString::fromStdString(PhoneData::instance().notificationSender.value());
}

void PhoneDataQml::qmlWriteNotificationSender(const QString &value)
{
    PhoneData::instance().notificationSender.setValue(value.toStdString());
}

QString PhoneDataQml::notificationText() const
{
    return QString::fromStdString(PhoneData::instance().notificationText.value());
}

void PhoneDataQml::qmlWriteNotificationText(const QString &value)
{
    PhoneData::instance().notificationText.setValue(value.toStdString());
}

void PhoneDataQml::mediaPlayPause()
{
    PhoneData::instance().mediaPlayPause();
}

void PhoneDataQml::mediaNext()
{
    PhoneData::instance().mediaNext();
}

void PhoneDataQml::mediaPrevious()
{
    PhoneData::instance().mediaPrevious();
}

void PhoneDataQml::answerCall()
{
    PhoneData::instance().answerCall();
}

void PhoneDataQml::rejectCall()
{
    PhoneData::instance().rejectCall();
}

PhoneListDataQml::PhoneListDataQml(QObject *parent)
    : QObject(parent)
{
    PhoneListData &d = PhoneListData::instance();
    d.contact0Name.setOnChanged([this] { emit contact0NameChanged(); });
    d.contact0Text.setOnChanged([this] { emit contact0TextChanged(); });
    d.contact0Initial.setOnChanged([this] { emit contact0InitialChanged(); });
    d.contact1Name.setOnChanged([this] { emit contact1NameChanged(); });
    d.contact1Text.setOnChanged([this] { emit contact1TextChanged(); });
    d.contact1Initial.setOnChanged([this] { emit contact1InitialChanged(); });
    d.contact2Name.setOnChanged([this] { emit contact2NameChanged(); });
    d.contact2Text.setOnChanged([this] { emit contact2TextChanged(); });
    d.contact2Initial.setOnChanged([this] { emit contact2InitialChanged(); });
    d.reminder0Name.setOnChanged([this] { emit reminder0NameChanged(); });
    d.reminder0Text.setOnChanged([this] { emit reminder0TextChanged(); });
    d.reminder0Initial.setOnChanged([this] { emit reminder0InitialChanged(); });
    d.reminder1Name.setOnChanged([this] { emit reminder1NameChanged(); });
    d.reminder1Text.setOnChanged([this] { emit reminder1TextChanged(); });
    d.reminder1Initial.setOnChanged([this] { emit reminder1InitialChanged(); });
    d.reminder2Name.setOnChanged([this] { emit reminder2NameChanged(); });
    d.reminder2Text.setOnChanged([this] { emit reminder2TextChanged(); });
    d.reminder2Initial.setOnChanged([this] { emit reminder2InitialChanged(); });
    d.contactCount.setOnChanged([this] { emit contactCountChanged(); });
    d.reminderCount.setOnChanged([this] { emit reminderCountChanged(); });
}

QString PhoneListDataQml::contact0Name() const
{
    return QString::fromStdString(PhoneListData::instance().contact0Name.value());
}

void PhoneListDataQml::qmlWriteContact0Name(const QString &value)
{
    PhoneListData::instance().contact0Name.setValue(value.toStdString());
}

QString PhoneListDataQml::contact0Text() const
{
    return QString::fromStdString(PhoneListData::instance().contact0Text.value());
}

void PhoneListDataQml::qmlWriteContact0Text(const QString &value)
{
    PhoneListData::instance().contact0Text.setValue(value.toStdString());
}

QString PhoneListDataQml::contact0Initial() const
{
    return QString::fromStdString(PhoneListData::instance().contact0Initial.value());
}

void PhoneListDataQml::qmlWriteContact0Initial(const QString &value)
{
    PhoneListData::instance().contact0Initial.setValue(value.toStdString());
}

QString PhoneListDataQml::contact1Name() const
{
    return QString::fromStdString(PhoneListData::instance().contact1Name.value());
}

void PhoneListDataQml::qmlWriteContact1Name(const QString &value)
{
    PhoneListData::instance().contact1Name.setValue(value.toStdString());
}

QString PhoneListDataQml::contact1Text() const
{
    return QString::fromStdString(PhoneListData::instance().contact1Text.value());
}

void PhoneListDataQml::qmlWriteContact1Text(const QString &value)
{
    PhoneListData::instance().contact1Text.setValue(value.toStdString());
}

QString PhoneListDataQml::contact1Initial() const
{
    return QString::fromStdString(PhoneListData::instance().contact1Initial.value());
}

void PhoneListDataQml::qmlWriteContact1Initial(const QString &value)
{
    PhoneListData::instance().contact1Initial.setValue(value.toStdString());
}

QString PhoneListDataQml::contact2Name() const
{
    return QString::fromStdString(PhoneListData::instance().contact2Name.value());
}

void PhoneListDataQml::qmlWriteContact2Name(const QString &value)
{
    PhoneListData::instance().contact2Name.setValue(value.toStdString());
}

QString PhoneListDataQml::contact2Text() const
{
    return QString::fromStdString(PhoneListData::instance().contact2Text.value());
}

void PhoneListDataQml::qmlWriteContact2Text(const QString &value)
{
    PhoneListData::instance().contact2Text.setValue(value.toStdString());
}

QString PhoneListDataQml::contact2Initial() const
{
    return QString::fromStdString(PhoneListData::instance().contact2Initial.value());
}

void PhoneListDataQml::qmlWriteContact2Initial(const QString &value)
{
    PhoneListData::instance().contact2Initial.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder0Name() const
{
    return QString::fromStdString(PhoneListData::instance().reminder0Name.value());
}

void PhoneListDataQml::qmlWriteReminder0Name(const QString &value)
{
    PhoneListData::instance().reminder0Name.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder0Text() const
{
    return QString::fromStdString(PhoneListData::instance().reminder0Text.value());
}

void PhoneListDataQml::qmlWriteReminder0Text(const QString &value)
{
    PhoneListData::instance().reminder0Text.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder0Initial() const
{
    return QString::fromStdString(PhoneListData::instance().reminder0Initial.value());
}

void PhoneListDataQml::qmlWriteReminder0Initial(const QString &value)
{
    PhoneListData::instance().reminder0Initial.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder1Name() const
{
    return QString::fromStdString(PhoneListData::instance().reminder1Name.value());
}

void PhoneListDataQml::qmlWriteReminder1Name(const QString &value)
{
    PhoneListData::instance().reminder1Name.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder1Text() const
{
    return QString::fromStdString(PhoneListData::instance().reminder1Text.value());
}

void PhoneListDataQml::qmlWriteReminder1Text(const QString &value)
{
    PhoneListData::instance().reminder1Text.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder1Initial() const
{
    return QString::fromStdString(PhoneListData::instance().reminder1Initial.value());
}

void PhoneListDataQml::qmlWriteReminder1Initial(const QString &value)
{
    PhoneListData::instance().reminder1Initial.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder2Name() const
{
    return QString::fromStdString(PhoneListData::instance().reminder2Name.value());
}

void PhoneListDataQml::qmlWriteReminder2Name(const QString &value)
{
    PhoneListData::instance().reminder2Name.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder2Text() const
{
    return QString::fromStdString(PhoneListData::instance().reminder2Text.value());
}

void PhoneListDataQml::qmlWriteReminder2Text(const QString &value)
{
    PhoneListData::instance().reminder2Text.setValue(value.toStdString());
}

QString PhoneListDataQml::reminder2Initial() const
{
    return QString::fromStdString(PhoneListData::instance().reminder2Initial.value());
}

void PhoneListDataQml::qmlWriteReminder2Initial(const QString &value)
{
    PhoneListData::instance().reminder2Initial.setValue(value.toStdString());
}

int PhoneListDataQml::contactCount() const
{
    return PhoneListData::instance().contactCount.value();
}

void PhoneListDataQml::qmlWriteContactCount(int value)
{
    PhoneListData::instance().contactCount.setValue(value);
}

int PhoneListDataQml::reminderCount() const
{
    return PhoneListData::instance().reminderCount.value();
}

void PhoneListDataQml::qmlWriteReminderCount(int value)
{
    PhoneListData::instance().reminderCount.setValue(value);
}

void PhoneListDataQml::clear()
{
    PhoneListData::instance().clear();
}

SimulatorQml::SimulatorQml(QObject *parent)
    : QObject(parent)
{
    Simulator &d = Simulator::instance();
    d.running.setOnChanged([this] { emit runningChanged(); });
    d.scenario.setOnChanged([this] { emit scenarioChanged(); });
    d.parked.setOnChanged([this] { emit parkedChanged(); });
}

bool SimulatorQml::running() const
{
    return Simulator::instance().running.value();
}

void SimulatorQml::qmlWriteRunning(bool value)
{
    Simulator::instance().running.setValue(value);
}

int SimulatorQml::scenario() const
{
    return Simulator::instance().scenario.value();
}

void SimulatorQml::qmlWriteScenario(int value)
{
    Simulator::instance().scenario.setValue(value);
}

bool SimulatorQml::parked() const
{
    return Simulator::instance().parked.value();
}

void SimulatorQml::qmlWriteParked(bool value)
{
    Simulator::instance().parked.setValue(value);
}

void SimulatorQml::step(int elapsedMs)
{
    Simulator::instance().step(elapsedMs);
}

void SimulatorQml::nextScenario()
{
    Simulator::instance().nextScenario();
}

void SimulatorQml::togglePark()
{
    Simulator::instance().togglePark();
}

SystemDataQml::SystemDataQml(QObject *parent)
    : QObject(parent)
{
    SystemData &d = SystemData::instance();
    d.hours.setOnChanged([this] { emit hoursChanged(); });
    d.minutes.setOnChanged([this] { emit minutesChanged(); });
    d.clockValid.setOnChanged([this] { emit clockValidChanged(); });
    d.use24Hour.setOnChanged([this] { emit use24HourChanged(); });
    d.nightMode.setOnChanged([this] { emit nightModeChanged(); });
    d.brightness.setOnChanged([this] { emit brightnessChanged(); });
    d.softwareDimming.setOnChanged([this] { emit softwareDimmingChanged(); });
    d.locked.setOnChanged([this] { emit lockedChanged(); });
    d.pinAttemptsLeft.setOnChanged([this] { emit pinAttemptsLeftChanged(); });
    d.demoMode.setOnChanged([this] { emit demoModeChanged(); });
    d.authState.setOnChanged([this] { emit authStateChanged(); });
    d.profileIndex.setOnChanged([this] { emit profileIndexChanged(); });
    d.seatLevel.setOnChanged([this] { emit seatLevelChanged(); });
    d.autoTurnOff.setOnChanged([this] { emit autoTurnOffChanged(); });
    d.speedoStyle.setOnChanged([this] { emit speedoStyleChanged(); });
    d.antiTheftArmed.setOnChanged([this] { emit antiTheftArmedChanged(); });
    d.theftCaptures.setOnChanged([this] { emit theftCapturesChanged(); });
    d.profile0Name.setOnChanged([this] { emit profile0NameChanged(); });
    d.profile1Name.setOnChanged([this] { emit profile1NameChanged(); });
    d.profile2Name.setOnChanged([this] { emit profile2NameChanged(); });
}

int SystemDataQml::hours() const
{
    return SystemData::instance().hours.value();
}

void SystemDataQml::qmlWriteHours(int value)
{
    SystemData::instance().hours.setValue(value);
}

int SystemDataQml::minutes() const
{
    return SystemData::instance().minutes.value();
}

void SystemDataQml::qmlWriteMinutes(int value)
{
    SystemData::instance().minutes.setValue(value);
}

bool SystemDataQml::clockValid() const
{
    return SystemData::instance().clockValid.value();
}

void SystemDataQml::qmlWriteClockValid(bool value)
{
    SystemData::instance().clockValid.setValue(value);
}

bool SystemDataQml::use24Hour() const
{
    return SystemData::instance().use24Hour.value();
}

void SystemDataQml::qmlWriteUse24Hour(bool value)
{
    SystemData::instance().use24Hour.setValue(value);
}

bool SystemDataQml::nightMode() const
{
    return SystemData::instance().nightMode.value();
}

void SystemDataQml::qmlWriteNightMode(bool value)
{
    SystemData::instance().nightMode.setValue(value);
}

int SystemDataQml::brightness() const
{
    return SystemData::instance().brightness.value();
}

void SystemDataQml::qmlWriteBrightness(int value)
{
    SystemData::instance().brightness.setValue(value);
}

bool SystemDataQml::softwareDimming() const
{
    return SystemData::instance().softwareDimming.value();
}

void SystemDataQml::qmlWriteSoftwareDimming(bool value)
{
    SystemData::instance().softwareDimming.setValue(value);
}

bool SystemDataQml::locked() const
{
    return SystemData::instance().locked.value();
}

void SystemDataQml::qmlWriteLocked(bool value)
{
    SystemData::instance().locked.setValue(value);
}

int SystemDataQml::pinAttemptsLeft() const
{
    return SystemData::instance().pinAttemptsLeft.value();
}

void SystemDataQml::qmlWritePinAttemptsLeft(int value)
{
    SystemData::instance().pinAttemptsLeft.setValue(value);
}

bool SystemDataQml::demoMode() const
{
    return SystemData::instance().demoMode.value();
}

void SystemDataQml::qmlWriteDemoMode(bool value)
{
    SystemData::instance().demoMode.setValue(value);
}

int SystemDataQml::authState() const
{
    return SystemData::instance().authState.value();
}

void SystemDataQml::qmlWriteAuthState(int value)
{
    SystemData::instance().authState.setValue(value);
}

int SystemDataQml::profileIndex() const
{
    return SystemData::instance().profileIndex.value();
}

void SystemDataQml::qmlWriteProfileIndex(int value)
{
    SystemData::instance().profileIndex.setValue(value);
}

int SystemDataQml::seatLevel() const
{
    return SystemData::instance().seatLevel.value();
}

void SystemDataQml::qmlWriteSeatLevel(int value)
{
    SystemData::instance().seatLevel.setValue(value);
}

bool SystemDataQml::autoTurnOff() const
{
    return SystemData::instance().autoTurnOff.value();
}

void SystemDataQml::qmlWriteAutoTurnOff(bool value)
{
    SystemData::instance().autoTurnOff.setValue(value);
}

int SystemDataQml::speedoStyle() const
{
    return SystemData::instance().speedoStyle.value();
}

void SystemDataQml::qmlWriteSpeedoStyle(int value)
{
    SystemData::instance().speedoStyle.setValue(value);
}

bool SystemDataQml::antiTheftArmed() const
{
    return SystemData::instance().antiTheftArmed.value();
}

void SystemDataQml::qmlWriteAntiTheftArmed(bool value)
{
    SystemData::instance().antiTheftArmed.setValue(value);
}

int SystemDataQml::theftCaptures() const
{
    return SystemData::instance().theftCaptures.value();
}

void SystemDataQml::qmlWriteTheftCaptures(int value)
{
    SystemData::instance().theftCaptures.setValue(value);
}

QString SystemDataQml::profile0Name() const
{
    return QString::fromStdString(SystemData::instance().profile0Name.value());
}

void SystemDataQml::qmlWriteProfile0Name(const QString &value)
{
    SystemData::instance().profile0Name.setValue(value.toStdString());
}

QString SystemDataQml::profile1Name() const
{
    return QString::fromStdString(SystemData::instance().profile1Name.value());
}

void SystemDataQml::qmlWriteProfile1Name(const QString &value)
{
    SystemData::instance().profile1Name.setValue(value.toStdString());
}

QString SystemDataQml::profile2Name() const
{
    return QString::fromStdString(SystemData::instance().profile2Name.value());
}

void SystemDataQml::qmlWriteProfile2Name(const QString &value)
{
    SystemData::instance().profile2Name.setValue(value.toStdString());
}

void SystemDataQml::tick()
{
    SystemData::instance().tick();
}

void SystemDataQml::poll()
{
    SystemData::instance().poll();
}

bool SystemDataQml::submitPin(int pin)
{
    return SystemData::instance().submitPin(pin);
}

void SystemDataQml::setBrightnessLevel(int level)
{
    SystemData::instance().setBrightnessLevel(level);
}

void SystemDataQml::toggleClockFormat()
{
    SystemData::instance().toggleClockFormat();
}

void SystemDataQml::setClock(int unixSeconds, int utcOffsetMinutes)
{
    SystemData::instance().setClock(unixSeconds, utcOffsetMinutes);
}

void SystemDataQml::selectProfile(int index)
{
    SystemData::instance().selectProfile(index);
}

void SystemDataQml::startScan()
{
    SystemData::instance().startScan();
}

void SystemDataQml::completeScan()
{
    SystemData::instance().completeScan();
}

void SystemDataQml::setSeatLevel(int level)
{
    SystemData::instance().setSeatLevel(level);
}

void SystemDataQml::toggleSpeedoStyle()
{
    SystemData::instance().toggleSpeedoStyle();
}

void SystemDataQml::clearTheftCaptures()
{
    SystemData::instance().clearTheftCaptures();
}

TripDataQml::TripDataQml(QObject *parent)
    : QObject(parent)
{
    TripData &d = TripData::instance();
    d.rideMinutes.setOnChanged([this] { emit rideMinutesChanged(); });
    d.socUsedPercent.setOnChanged([this] { emit socUsedPercentChanged(); });
    d.ecoShare.setOnChanged([this] { emit ecoShareChanged(); });
    d.normalShare.setOnChanged([this] { emit normalShareChanged(); });
    d.sportShare.setOnChanged([this] { emit sportShareChanged(); });
    d.recorded.setOnChanged([this] { emit recordedChanged(); });
}

int TripDataQml::rideMinutes() const
{
    return TripData::instance().rideMinutes.value();
}

void TripDataQml::qmlWriteRideMinutes(int value)
{
    TripData::instance().rideMinutes.setValue(value);
}

int TripDataQml::socUsedPercent() const
{
    return TripData::instance().socUsedPercent.value();
}

void TripDataQml::qmlWriteSocUsedPercent(int value)
{
    TripData::instance().socUsedPercent.setValue(value);
}

int TripDataQml::ecoShare() const
{
    return TripData::instance().ecoShare.value();
}

void TripDataQml::qmlWriteEcoShare(int value)
{
    TripData::instance().ecoShare.setValue(value);
}

int TripDataQml::normalShare() const
{
    return TripData::instance().normalShare.value();
}

void TripDataQml::qmlWriteNormalShare(int value)
{
    TripData::instance().normalShare.setValue(value);
}

int TripDataQml::sportShare() const
{
    return TripData::instance().sportShare.value();
}

void TripDataQml::qmlWriteSportShare(int value)
{
    TripData::instance().sportShare.setValue(value);
}

bool TripDataQml::recorded() const
{
    return TripData::instance().recorded.value();
}

void TripDataQml::qmlWriteRecorded(bool value)
{
    TripData::instance().recorded.setValue(value);
}

void TripDataQml::reset()
{
    TripData::instance().reset();
}

VehicleDataQml::VehicleDataQml(QObject *parent)
    : QObject(parent)
{
    VehicleData &d = VehicleData::instance();
    d.speedKmh.setOnChanged([this] { emit speedKmhChanged(); });
    d.motorRpm.setOnChanged([this] { emit motorRpmChanged(); });
    d.powerPercent.setOnChanged([this] { emit powerPercentChanged(); });
    d.rideMode.setOnChanged([this] { emit rideModeChanged(); });
    d.driveState.setOnChanged([this] { emit driveStateChanged(); });
    d.readyToRide.setOnChanged([this] { emit readyToRideChanged(); });
    d.sideStandDown.setOnChanged([this] { emit sideStandDownChanged(); });
    d.batteryPercent.setOnChanged([this] { emit batteryPercentChanged(); });
    d.packVoltageX10.setOnChanged([this] { emit packVoltageX10Changed(); });
    d.packCurrentAx10.setOnChanged([this] { emit packCurrentAx10Changed(); });
    d.packTempC.setOnChanged([this] { emit packTempCChanged(); });
    d.motorTempC.setOnChanged([this] { emit motorTempCChanged(); });
    d.controllerTempC.setOnChanged([this] { emit controllerTempCChanged(); });
    d.ambientTempC.setOnChanged([this] { emit ambientTempCChanged(); });
    d.chargeState.setOnChanged([this] { emit chargeStateChanged(); });
    d.rangeKm.setOnChanged([this] { emit rangeKmChanged(); });
    d.indicatorLeft.setOnChanged([this] { emit indicatorLeftChanged(); });
    d.indicatorRight.setOnChanged([this] { emit indicatorRightChanged(); });
    d.highBeam.setOnChanged([this] { emit highBeamChanged(); });
    d.lowBeam.setOnChanged([this] { emit lowBeamChanged(); });
    d.hazard.setOnChanged([this] { emit hazardChanged(); });
    d.absFault.setOnChanged([this] { emit absFaultChanged(); });
    d.absActive.setOnChanged([this] { emit absActiveChanged(); });
    d.tyreFrontPsiX10.setOnChanged([this] { emit tyreFrontPsiX10Changed(); });
    d.tyreRearPsiX10.setOnChanged([this] { emit tyreRearPsiX10Changed(); });
    d.odometerKm.setOnChanged([this] { emit odometerKmChanged(); });
    d.tripKmX10.setOnChanged([this] { emit tripKmX10Changed(); });
    d.faultCode.setOnChanged([this] { emit faultCodeChanged(); });
    d.crashDetected.setOnChanged([this] { emit crashDetectedChanged(); });
    d.driveStale.setOnChanged([this] { emit driveStaleChanged(); });
    d.batteryStale.setOnChanged([this] { emit batteryStaleChanged(); });
    d.lampsStale.setOnChanged([this] { emit lampsStaleChanged(); });
}

int VehicleDataQml::speedKmh() const
{
    return VehicleData::instance().speedKmh.value();
}

void VehicleDataQml::qmlWriteSpeedKmh(int value)
{
    VehicleData::instance().speedKmh.setValue(value);
}

int VehicleDataQml::motorRpm() const
{
    return VehicleData::instance().motorRpm.value();
}

void VehicleDataQml::qmlWriteMotorRpm(int value)
{
    VehicleData::instance().motorRpm.setValue(value);
}

int VehicleDataQml::powerPercent() const
{
    return VehicleData::instance().powerPercent.value();
}

void VehicleDataQml::qmlWritePowerPercent(int value)
{
    VehicleData::instance().powerPercent.setValue(value);
}

int VehicleDataQml::rideMode() const
{
    return VehicleData::instance().rideMode.value();
}

void VehicleDataQml::qmlWriteRideMode(int value)
{
    VehicleData::instance().rideMode.setValue(value);
}

int VehicleDataQml::driveState() const
{
    return VehicleData::instance().driveState.value();
}

void VehicleDataQml::qmlWriteDriveState(int value)
{
    VehicleData::instance().driveState.setValue(value);
}

bool VehicleDataQml::readyToRide() const
{
    return VehicleData::instance().readyToRide.value();
}

void VehicleDataQml::qmlWriteReadyToRide(bool value)
{
    VehicleData::instance().readyToRide.setValue(value);
}

bool VehicleDataQml::sideStandDown() const
{
    return VehicleData::instance().sideStandDown.value();
}

void VehicleDataQml::qmlWriteSideStandDown(bool value)
{
    VehicleData::instance().sideStandDown.setValue(value);
}

int VehicleDataQml::batteryPercent() const
{
    return VehicleData::instance().batteryPercent.value();
}

void VehicleDataQml::qmlWriteBatteryPercent(int value)
{
    VehicleData::instance().batteryPercent.setValue(value);
}

int VehicleDataQml::packVoltageX10() const
{
    return VehicleData::instance().packVoltageX10.value();
}

void VehicleDataQml::qmlWritePackVoltageX10(int value)
{
    VehicleData::instance().packVoltageX10.setValue(value);
}

int VehicleDataQml::packCurrentAx10() const
{
    return VehicleData::instance().packCurrentAx10.value();
}

void VehicleDataQml::qmlWritePackCurrentAx10(int value)
{
    VehicleData::instance().packCurrentAx10.setValue(value);
}

int VehicleDataQml::packTempC() const
{
    return VehicleData::instance().packTempC.value();
}

void VehicleDataQml::qmlWritePackTempC(int value)
{
    VehicleData::instance().packTempC.setValue(value);
}

int VehicleDataQml::motorTempC() const
{
    return VehicleData::instance().motorTempC.value();
}

void VehicleDataQml::qmlWriteMotorTempC(int value)
{
    VehicleData::instance().motorTempC.setValue(value);
}

int VehicleDataQml::controllerTempC() const
{
    return VehicleData::instance().controllerTempC.value();
}

void VehicleDataQml::qmlWriteControllerTempC(int value)
{
    VehicleData::instance().controllerTempC.setValue(value);
}

int VehicleDataQml::ambientTempC() const
{
    return VehicleData::instance().ambientTempC.value();
}

void VehicleDataQml::qmlWriteAmbientTempC(int value)
{
    VehicleData::instance().ambientTempC.setValue(value);
}

int VehicleDataQml::chargeState() const
{
    return VehicleData::instance().chargeState.value();
}

void VehicleDataQml::qmlWriteChargeState(int value)
{
    VehicleData::instance().chargeState.setValue(value);
}

int VehicleDataQml::rangeKm() const
{
    return VehicleData::instance().rangeKm.value();
}

void VehicleDataQml::qmlWriteRangeKm(int value)
{
    VehicleData::instance().rangeKm.setValue(value);
}

bool VehicleDataQml::indicatorLeft() const
{
    return VehicleData::instance().indicatorLeft.value();
}

void VehicleDataQml::qmlWriteIndicatorLeft(bool value)
{
    VehicleData::instance().indicatorLeft.setValue(value);
}

bool VehicleDataQml::indicatorRight() const
{
    return VehicleData::instance().indicatorRight.value();
}

void VehicleDataQml::qmlWriteIndicatorRight(bool value)
{
    VehicleData::instance().indicatorRight.setValue(value);
}

bool VehicleDataQml::highBeam() const
{
    return VehicleData::instance().highBeam.value();
}

void VehicleDataQml::qmlWriteHighBeam(bool value)
{
    VehicleData::instance().highBeam.setValue(value);
}

bool VehicleDataQml::lowBeam() const
{
    return VehicleData::instance().lowBeam.value();
}

void VehicleDataQml::qmlWriteLowBeam(bool value)
{
    VehicleData::instance().lowBeam.setValue(value);
}

bool VehicleDataQml::hazard() const
{
    return VehicleData::instance().hazard.value();
}

void VehicleDataQml::qmlWriteHazard(bool value)
{
    VehicleData::instance().hazard.setValue(value);
}

bool VehicleDataQml::absFault() const
{
    return VehicleData::instance().absFault.value();
}

void VehicleDataQml::qmlWriteAbsFault(bool value)
{
    VehicleData::instance().absFault.setValue(value);
}

bool VehicleDataQml::absActive() const
{
    return VehicleData::instance().absActive.value();
}

void VehicleDataQml::qmlWriteAbsActive(bool value)
{
    VehicleData::instance().absActive.setValue(value);
}

int VehicleDataQml::tyreFrontPsiX10() const
{
    return VehicleData::instance().tyreFrontPsiX10.value();
}

void VehicleDataQml::qmlWriteTyreFrontPsiX10(int value)
{
    VehicleData::instance().tyreFrontPsiX10.setValue(value);
}

int VehicleDataQml::tyreRearPsiX10() const
{
    return VehicleData::instance().tyreRearPsiX10.value();
}

void VehicleDataQml::qmlWriteTyreRearPsiX10(int value)
{
    VehicleData::instance().tyreRearPsiX10.setValue(value);
}

int VehicleDataQml::odometerKm() const
{
    return VehicleData::instance().odometerKm.value();
}

void VehicleDataQml::qmlWriteOdometerKm(int value)
{
    VehicleData::instance().odometerKm.setValue(value);
}

int VehicleDataQml::tripKmX10() const
{
    return VehicleData::instance().tripKmX10.value();
}

void VehicleDataQml::qmlWriteTripKmX10(int value)
{
    VehicleData::instance().tripKmX10.setValue(value);
}

int VehicleDataQml::faultCode() const
{
    return VehicleData::instance().faultCode.value();
}

void VehicleDataQml::qmlWriteFaultCode(int value)
{
    VehicleData::instance().faultCode.setValue(value);
}

bool VehicleDataQml::crashDetected() const
{
    return VehicleData::instance().crashDetected.value();
}

void VehicleDataQml::qmlWriteCrashDetected(bool value)
{
    VehicleData::instance().crashDetected.setValue(value);
}

bool VehicleDataQml::driveStale() const
{
    return VehicleData::instance().driveStale.value();
}

void VehicleDataQml::qmlWriteDriveStale(bool value)
{
    VehicleData::instance().driveStale.setValue(value);
}

bool VehicleDataQml::batteryStale() const
{
    return VehicleData::instance().batteryStale.value();
}

void VehicleDataQml::qmlWriteBatteryStale(bool value)
{
    VehicleData::instance().batteryStale.setValue(value);
}

bool VehicleDataQml::lampsStale() const
{
    return VehicleData::instance().lampsStale.value();
}

void VehicleDataQml::qmlWriteLampsStale(bool value)
{
    VehicleData::instance().lampsStale.setValue(value);
}

void VehicleDataQml::applySignal(int signalId, int value)
{
    VehicleData::instance().applySignal(signalId, value);
}
