// Generated by tools/generate_desktop_bridge.py. Do not edit.
#pragma once

#include <QObject>
#include <QString>
#include <QtQml/qqmlregistration.h>

class AlertDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(AlertData)
    QML_SINGLETON
    Q_PROPERTY(int kind READ kind WRITE qmlWriteKind NOTIFY kindChanged FINAL)
    Q_PROPERTY(int level READ level WRITE qmlWriteLevel NOTIFY levelChanged FINAL)
    Q_PROPERTY(bool popupVisible READ popupVisible WRITE qmlWritePopupVisible NOTIFY popupVisibleChanged FINAL)
    Q_PROPERTY(int phase READ phase WRITE qmlWritePhase NOTIFY phaseChanged FINAL)
    Q_PROPERTY(int sosSecondsLeft READ sosSecondsLeft WRITE qmlWriteSosSecondsLeft NOTIFY sosSecondsLeftChanged FINAL)
    Q_PROPERTY(bool sosSent READ sosSent WRITE qmlWriteSosSent NOTIFY sosSentChanged FINAL)
    Q_PROPERTY(int protocolIndex READ protocolIndex WRITE qmlWriteProtocolIndex NOTIFY protocolIndexChanged FINAL)
    Q_PROPERTY(int activeProtocol READ activeProtocol WRITE qmlWriteActiveProtocol NOTIFY activeProtocolChanged FINAL)

public:
    enum Kind { NoAlert = 0, LowTyreFront, LowTyreRear, LowBattery, SideStandDown, AbsFault, MotorOverheat, BatteryOverheat, CommunicationLost, CrashDetected };
    Q_ENUM(Kind)
    enum Level { LevelNone = 0, LevelInfo, LevelWarning, LevelCritical };
    Q_ENUM(Level)
    explicit AlertDataQml(QObject *parent = nullptr);

    int kind() const;
    void qmlWriteKind(int value);
    int level() const;
    void qmlWriteLevel(int value);
    bool popupVisible() const;
    void qmlWritePopupVisible(bool value);
    int phase() const;
    void qmlWritePhase(int value);
    int sosSecondsLeft() const;
    void qmlWriteSosSecondsLeft(int value);
    bool sosSent() const;
    void qmlWriteSosSent(bool value);
    int protocolIndex() const;
    void qmlWriteProtocolIndex(int value);
    int activeProtocol() const;
    void qmlWriteActiveProtocol(int value);
    Q_INVOKABLE void acknowledge();
    Q_INVOKABLE void update(int newKind, int newLevel);
    Q_INVOKABLE void tickSecond();
    Q_INVOKABLE void cancelSos();
    Q_INVOKABLE void activateProtocol();

signals:
    void kindChanged();
    void levelChanged();
    void popupVisibleChanged();
    void phaseChanged();
    void sosSecondsLeftChanged();
    void sosSentChanged();
    void protocolIndexChanged();
    void activeProtocolChanged();
};

class ClusterInputQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(ClusterInput)
    QML_SINGLETON

public:
    enum Button { Up = 0, Down, Left, Right, Ok, Mode, Back };
    Q_ENUM(Button)
    enum Action { Press = 0, LongPress };
    Q_ENUM(Action)
    explicit ClusterInputQml(QObject *parent = nullptr);

    Q_INVOKABLE void inject(int button, int action);

signals:
    void buttonEvent(int button, int action);
};

class NavigationDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(NavigationData)
    QML_SINGLETON
    Q_PROPERTY(bool active READ active WRITE qmlWriteActive NOTIFY activeChanged FINAL)
    Q_PROPERTY(int maneuver READ maneuver WRITE qmlWriteManeuver NOTIFY maneuverChanged FINAL)
    Q_PROPERTY(int roundaboutExit READ roundaboutExit WRITE qmlWriteRoundaboutExit NOTIFY roundaboutExitChanged FINAL)
    Q_PROPERTY(int distanceToManeuverM READ distanceToManeuverM WRITE qmlWriteDistanceToManeuverM NOTIFY distanceToManeuverMChanged FINAL)
    Q_PROPERTY(int distanceRemainingM READ distanceRemainingM WRITE qmlWriteDistanceRemainingM NOTIFY distanceRemainingMChanged FINAL)
    Q_PROPERTY(int etaMinutes READ etaMinutes WRITE qmlWriteEtaMinutes NOTIFY etaMinutesChanged FINAL)
    Q_PROPERTY(int laneMask READ laneMask WRITE qmlWriteLaneMask NOTIFY laneMaskChanged FINAL)
    Q_PROPERTY(int recommendedLaneMask READ recommendedLaneMask WRITE qmlWriteRecommendedLaneMask NOTIFY recommendedLaneMaskChanged FINAL)
    Q_PROPERTY(QString roadName READ roadName WRITE qmlWriteRoadName NOTIFY roadNameChanged FINAL)

public:
    enum Maneuver { None = 0, Straight, SlightLeft, Left, SharpLeft, SlightRight, Right, SharpRight, UTurnLeft, UTurnRight, RoundaboutEnter, RoundaboutExit, ForkLeft, ForkRight, MergeLeft, MergeRight, Destination };
    Q_ENUM(Maneuver)
    explicit NavigationDataQml(QObject *parent = nullptr);

    bool active() const;
    void qmlWriteActive(bool value);
    int maneuver() const;
    void qmlWriteManeuver(int value);
    int roundaboutExit() const;
    void qmlWriteRoundaboutExit(int value);
    int distanceToManeuverM() const;
    void qmlWriteDistanceToManeuverM(int value);
    int distanceRemainingM() const;
    void qmlWriteDistanceRemainingM(int value);
    int etaMinutes() const;
    void qmlWriteEtaMinutes(int value);
    int laneMask() const;
    void qmlWriteLaneMask(int value);
    int recommendedLaneMask() const;
    void qmlWriteRecommendedLaneMask(int value);
    QString roadName() const;
    void qmlWriteRoadName(const QString &value);
    Q_INVOKABLE void clear();

signals:
    void activeChanged();
    void maneuverChanged();
    void roundaboutExitChanged();
    void distanceToManeuverMChanged();
    void distanceRemainingMChanged();
    void etaMinutesChanged();
    void laneMaskChanged();
    void recommendedLaneMaskChanged();
    void roadNameChanged();
};

class PhoneDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(PhoneData)
    QML_SINGLETON
    Q_PROPERTY(bool connected READ connected WRITE qmlWriteConnected NOTIFY connectedChanged FINAL)
    Q_PROPERTY(int batteryPercent READ batteryPercent WRITE qmlWriteBatteryPercent NOTIFY batteryPercentChanged FINAL)
    Q_PROPERTY(int signalBars READ signalBars WRITE qmlWriteSignalBars NOTIFY signalBarsChanged FINAL)
    Q_PROPERTY(bool internet READ internet WRITE qmlWriteInternet NOTIFY internetChanged FINAL)
    Q_PROPERTY(int callStatus READ callStatus WRITE qmlWriteCallStatus NOTIFY callStatusChanged FINAL)
    Q_PROPERTY(QString callerName READ callerName WRITE qmlWriteCallerName NOTIFY callerNameChanged FINAL)
    Q_PROPERTY(bool mediaPlaying READ mediaPlaying WRITE qmlWriteMediaPlaying NOTIFY mediaPlayingChanged FINAL)
    Q_PROPERTY(int volume READ volume WRITE qmlWriteVolume NOTIFY volumeChanged FINAL)
    Q_PROPERTY(int trackPositionS READ trackPositionS WRITE qmlWriteTrackPositionS NOTIFY trackPositionSChanged FINAL)
    Q_PROPERTY(int trackDurationS READ trackDurationS WRITE qmlWriteTrackDurationS NOTIFY trackDurationSChanged FINAL)
    Q_PROPERTY(QString trackTitle READ trackTitle WRITE qmlWriteTrackTitle NOTIFY trackTitleChanged FINAL)
    Q_PROPERTY(QString trackArtist READ trackArtist WRITE qmlWriteTrackArtist NOTIFY trackArtistChanged FINAL)
    Q_PROPERTY(int notificationSeq READ notificationSeq WRITE qmlWriteNotificationSeq NOTIFY notificationSeqChanged FINAL)
    Q_PROPERTY(QString notificationSender READ notificationSender WRITE qmlWriteNotificationSender NOTIFY notificationSenderChanged FINAL)
    Q_PROPERTY(QString notificationText READ notificationText WRITE qmlWriteNotificationText NOTIFY notificationTextChanged FINAL)

public:
    enum CallStatus { Idle = 0, Ringing = 1, Active = 2 };
    Q_ENUM(CallStatus)
    explicit PhoneDataQml(QObject *parent = nullptr);

    bool connected() const;
    void qmlWriteConnected(bool value);
    int batteryPercent() const;
    void qmlWriteBatteryPercent(int value);
    int signalBars() const;
    void qmlWriteSignalBars(int value);
    bool internet() const;
    void qmlWriteInternet(bool value);
    int callStatus() const;
    void qmlWriteCallStatus(int value);
    QString callerName() const;
    void qmlWriteCallerName(const QString &value);
    bool mediaPlaying() const;
    void qmlWriteMediaPlaying(bool value);
    int volume() const;
    void qmlWriteVolume(int value);
    int trackPositionS() const;
    void qmlWriteTrackPositionS(int value);
    int trackDurationS() const;
    void qmlWriteTrackDurationS(int value);
    QString trackTitle() const;
    void qmlWriteTrackTitle(const QString &value);
    QString trackArtist() const;
    void qmlWriteTrackArtist(const QString &value);
    int notificationSeq() const;
    void qmlWriteNotificationSeq(int value);
    QString notificationSender() const;
    void qmlWriteNotificationSender(const QString &value);
    QString notificationText() const;
    void qmlWriteNotificationText(const QString &value);
    Q_INVOKABLE void mediaPlayPause();
    Q_INVOKABLE void mediaNext();
    Q_INVOKABLE void mediaPrevious();
    Q_INVOKABLE void answerCall();
    Q_INVOKABLE void rejectCall();

signals:
    void connectedChanged();
    void batteryPercentChanged();
    void signalBarsChanged();
    void internetChanged();
    void callStatusChanged();
    void callerNameChanged();
    void mediaPlayingChanged();
    void volumeChanged();
    void trackPositionSChanged();
    void trackDurationSChanged();
    void trackTitleChanged();
    void trackArtistChanged();
    void notificationSeqChanged();
    void notificationSenderChanged();
    void notificationTextChanged();
};

class PhoneListDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(PhoneListData)
    QML_SINGLETON
    Q_PROPERTY(QString contact0Name READ contact0Name WRITE qmlWriteContact0Name NOTIFY contact0NameChanged FINAL)
    Q_PROPERTY(QString contact0Text READ contact0Text WRITE qmlWriteContact0Text NOTIFY contact0TextChanged FINAL)
    Q_PROPERTY(QString contact0Initial READ contact0Initial WRITE qmlWriteContact0Initial NOTIFY contact0InitialChanged FINAL)
    Q_PROPERTY(QString contact1Name READ contact1Name WRITE qmlWriteContact1Name NOTIFY contact1NameChanged FINAL)
    Q_PROPERTY(QString contact1Text READ contact1Text WRITE qmlWriteContact1Text NOTIFY contact1TextChanged FINAL)
    Q_PROPERTY(QString contact1Initial READ contact1Initial WRITE qmlWriteContact1Initial NOTIFY contact1InitialChanged FINAL)
    Q_PROPERTY(QString contact2Name READ contact2Name WRITE qmlWriteContact2Name NOTIFY contact2NameChanged FINAL)
    Q_PROPERTY(QString contact2Text READ contact2Text WRITE qmlWriteContact2Text NOTIFY contact2TextChanged FINAL)
    Q_PROPERTY(QString contact2Initial READ contact2Initial WRITE qmlWriteContact2Initial NOTIFY contact2InitialChanged FINAL)
    Q_PROPERTY(QString reminder0Name READ reminder0Name WRITE qmlWriteReminder0Name NOTIFY reminder0NameChanged FINAL)
    Q_PROPERTY(QString reminder0Text READ reminder0Text WRITE qmlWriteReminder0Text NOTIFY reminder0TextChanged FINAL)
    Q_PROPERTY(QString reminder0Initial READ reminder0Initial WRITE qmlWriteReminder0Initial NOTIFY reminder0InitialChanged FINAL)
    Q_PROPERTY(QString reminder1Name READ reminder1Name WRITE qmlWriteReminder1Name NOTIFY reminder1NameChanged FINAL)
    Q_PROPERTY(QString reminder1Text READ reminder1Text WRITE qmlWriteReminder1Text NOTIFY reminder1TextChanged FINAL)
    Q_PROPERTY(QString reminder1Initial READ reminder1Initial WRITE qmlWriteReminder1Initial NOTIFY reminder1InitialChanged FINAL)
    Q_PROPERTY(QString reminder2Name READ reminder2Name WRITE qmlWriteReminder2Name NOTIFY reminder2NameChanged FINAL)
    Q_PROPERTY(QString reminder2Text READ reminder2Text WRITE qmlWriteReminder2Text NOTIFY reminder2TextChanged FINAL)
    Q_PROPERTY(QString reminder2Initial READ reminder2Initial WRITE qmlWriteReminder2Initial NOTIFY reminder2InitialChanged FINAL)
    Q_PROPERTY(int contactCount READ contactCount WRITE qmlWriteContactCount NOTIFY contactCountChanged FINAL)
    Q_PROPERTY(int reminderCount READ reminderCount WRITE qmlWriteReminderCount NOTIFY reminderCountChanged FINAL)

public:
    explicit PhoneListDataQml(QObject *parent = nullptr);

    QString contact0Name() const;
    void qmlWriteContact0Name(const QString &value);
    QString contact0Text() const;
    void qmlWriteContact0Text(const QString &value);
    QString contact0Initial() const;
    void qmlWriteContact0Initial(const QString &value);
    QString contact1Name() const;
    void qmlWriteContact1Name(const QString &value);
    QString contact1Text() const;
    void qmlWriteContact1Text(const QString &value);
    QString contact1Initial() const;
    void qmlWriteContact1Initial(const QString &value);
    QString contact2Name() const;
    void qmlWriteContact2Name(const QString &value);
    QString contact2Text() const;
    void qmlWriteContact2Text(const QString &value);
    QString contact2Initial() const;
    void qmlWriteContact2Initial(const QString &value);
    QString reminder0Name() const;
    void qmlWriteReminder0Name(const QString &value);
    QString reminder0Text() const;
    void qmlWriteReminder0Text(const QString &value);
    QString reminder0Initial() const;
    void qmlWriteReminder0Initial(const QString &value);
    QString reminder1Name() const;
    void qmlWriteReminder1Name(const QString &value);
    QString reminder1Text() const;
    void qmlWriteReminder1Text(const QString &value);
    QString reminder1Initial() const;
    void qmlWriteReminder1Initial(const QString &value);
    QString reminder2Name() const;
    void qmlWriteReminder2Name(const QString &value);
    QString reminder2Text() const;
    void qmlWriteReminder2Text(const QString &value);
    QString reminder2Initial() const;
    void qmlWriteReminder2Initial(const QString &value);
    int contactCount() const;
    void qmlWriteContactCount(int value);
    int reminderCount() const;
    void qmlWriteReminderCount(int value);
    Q_INVOKABLE void clear();

signals:
    void contact0NameChanged();
    void contact0TextChanged();
    void contact0InitialChanged();
    void contact1NameChanged();
    void contact1TextChanged();
    void contact1InitialChanged();
    void contact2NameChanged();
    void contact2TextChanged();
    void contact2InitialChanged();
    void reminder0NameChanged();
    void reminder0TextChanged();
    void reminder0InitialChanged();
    void reminder1NameChanged();
    void reminder1TextChanged();
    void reminder1InitialChanged();
    void reminder2NameChanged();
    void reminder2TextChanged();
    void reminder2InitialChanged();
    void contactCountChanged();
    void reminderCountChanged();
};

class SimulatorQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(Simulator)
    QML_SINGLETON
    Q_PROPERTY(bool running READ running WRITE qmlWriteRunning NOTIFY runningChanged FINAL)
    Q_PROPERTY(int scenario READ scenario WRITE qmlWriteScenario NOTIFY scenarioChanged FINAL)
    Q_PROPERTY(bool parked READ parked WRITE qmlWriteParked NOTIFY parkedChanged FINAL)

public:
    explicit SimulatorQml(QObject *parent = nullptr);

    bool running() const;
    void qmlWriteRunning(bool value);
    int scenario() const;
    void qmlWriteScenario(int value);
    bool parked() const;
    void qmlWriteParked(bool value);
    Q_INVOKABLE void step(int elapsedMs);
    Q_INVOKABLE void nextScenario();
    Q_INVOKABLE void togglePark();

signals:
    void runningChanged();
    void scenarioChanged();
    void parkedChanged();
};

class SystemDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(SystemData)
    QML_SINGLETON
    Q_PROPERTY(int hours READ hours WRITE qmlWriteHours NOTIFY hoursChanged FINAL)
    Q_PROPERTY(int minutes READ minutes WRITE qmlWriteMinutes NOTIFY minutesChanged FINAL)
    Q_PROPERTY(bool clockValid READ clockValid WRITE qmlWriteClockValid NOTIFY clockValidChanged FINAL)
    Q_PROPERTY(bool use24Hour READ use24Hour WRITE qmlWriteUse24Hour NOTIFY use24HourChanged FINAL)
    Q_PROPERTY(bool useMiles READ useMiles WRITE qmlWriteUseMiles NOTIFY useMilesChanged FINAL)
    Q_PROPERTY(bool nightMode READ nightMode WRITE qmlWriteNightMode NOTIFY nightModeChanged FINAL)
    Q_PROPERTY(int brightness READ brightness WRITE qmlWriteBrightness NOTIFY brightnessChanged FINAL)
    Q_PROPERTY(bool softwareDimming READ softwareDimming WRITE qmlWriteSoftwareDimming NOTIFY softwareDimmingChanged FINAL)
    Q_PROPERTY(bool locked READ locked WRITE qmlWriteLocked NOTIFY lockedChanged FINAL)
    Q_PROPERTY(int pinAttemptsLeft READ pinAttemptsLeft WRITE qmlWritePinAttemptsLeft NOTIFY pinAttemptsLeftChanged FINAL)
    Q_PROPERTY(bool demoMode READ demoMode WRITE qmlWriteDemoMode NOTIFY demoModeChanged FINAL)
    Q_PROPERTY(int authState READ authState WRITE qmlWriteAuthState NOTIFY authStateChanged FINAL)
    Q_PROPERTY(int profileIndex READ profileIndex WRITE qmlWriteProfileIndex NOTIFY profileIndexChanged FINAL)
    Q_PROPERTY(int seatLevel READ seatLevel WRITE qmlWriteSeatLevel NOTIFY seatLevelChanged FINAL)
    Q_PROPERTY(bool autoTurnOff READ autoTurnOff WRITE qmlWriteAutoTurnOff NOTIFY autoTurnOffChanged FINAL)
    Q_PROPERTY(int speedoStyle READ speedoStyle WRITE qmlWriteSpeedoStyle NOTIFY speedoStyleChanged FINAL)
    Q_PROPERTY(bool antiTheftArmed READ antiTheftArmed WRITE qmlWriteAntiTheftArmed NOTIFY antiTheftArmedChanged FINAL)
    Q_PROPERTY(int theftCaptures READ theftCaptures WRITE qmlWriteTheftCaptures NOTIFY theftCapturesChanged FINAL)
    Q_PROPERTY(QString profile0Name READ profile0Name WRITE qmlWriteProfile0Name NOTIFY profile0NameChanged FINAL)
    Q_PROPERTY(QString profile1Name READ profile1Name WRITE qmlWriteProfile1Name NOTIFY profile1NameChanged FINAL)
    Q_PROPERTY(QString profile2Name READ profile2Name WRITE qmlWriteProfile2Name NOTIFY profile2NameChanged FINAL)

public:
    enum AuthState { AuthIdle = 0, AuthScanning, AuthMatched, AuthDenied };
    Q_ENUM(AuthState)
    enum SpeedoStyle { SpeedoClassic = 0, SpeedoHex };
    Q_ENUM(SpeedoStyle)
    explicit SystemDataQml(QObject *parent = nullptr);

    int hours() const;
    void qmlWriteHours(int value);
    int minutes() const;
    void qmlWriteMinutes(int value);
    bool clockValid() const;
    void qmlWriteClockValid(bool value);
    bool use24Hour() const;
    void qmlWriteUse24Hour(bool value);
    bool useMiles() const;
    void qmlWriteUseMiles(bool value);
    bool nightMode() const;
    void qmlWriteNightMode(bool value);
    int brightness() const;
    void qmlWriteBrightness(int value);
    bool softwareDimming() const;
    void qmlWriteSoftwareDimming(bool value);
    bool locked() const;
    void qmlWriteLocked(bool value);
    int pinAttemptsLeft() const;
    void qmlWritePinAttemptsLeft(int value);
    bool demoMode() const;
    void qmlWriteDemoMode(bool value);
    int authState() const;
    void qmlWriteAuthState(int value);
    int profileIndex() const;
    void qmlWriteProfileIndex(int value);
    int seatLevel() const;
    void qmlWriteSeatLevel(int value);
    bool autoTurnOff() const;
    void qmlWriteAutoTurnOff(bool value);
    int speedoStyle() const;
    void qmlWriteSpeedoStyle(int value);
    bool antiTheftArmed() const;
    void qmlWriteAntiTheftArmed(bool value);
    int theftCaptures() const;
    void qmlWriteTheftCaptures(int value);
    QString profile0Name() const;
    void qmlWriteProfile0Name(const QString &value);
    QString profile1Name() const;
    void qmlWriteProfile1Name(const QString &value);
    QString profile2Name() const;
    void qmlWriteProfile2Name(const QString &value);
    Q_INVOKABLE void tick();
    Q_INVOKABLE void poll();
    Q_INVOKABLE bool submitPin(int pin);
    Q_INVOKABLE void setBrightnessLevel(int level);
    Q_INVOKABLE void toggleClockFormat();
    Q_INVOKABLE void toggleUnits();
    Q_INVOKABLE void setClock(int unixSeconds, int utcOffsetMinutes);
    Q_INVOKABLE void selectProfile(int index);
    Q_INVOKABLE void startScan();
    Q_INVOKABLE void completeScan();
    Q_INVOKABLE void setSeatLevel(int level);
    Q_INVOKABLE void toggleSpeedoStyle();
    Q_INVOKABLE void clearTheftCaptures();

signals:
    void hoursChanged();
    void minutesChanged();
    void clockValidChanged();
    void use24HourChanged();
    void useMilesChanged();
    void nightModeChanged();
    void brightnessChanged();
    void softwareDimmingChanged();
    void lockedChanged();
    void pinAttemptsLeftChanged();
    void demoModeChanged();
    void authStateChanged();
    void profileIndexChanged();
    void seatLevelChanged();
    void autoTurnOffChanged();
    void speedoStyleChanged();
    void antiTheftArmedChanged();
    void theftCapturesChanged();
    void profile0NameChanged();
    void profile1NameChanged();
    void profile2NameChanged();
};

class TripDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(TripData)
    QML_SINGLETON
    Q_PROPERTY(int rideMinutes READ rideMinutes WRITE qmlWriteRideMinutes NOTIFY rideMinutesChanged FINAL)
    Q_PROPERTY(int socUsedPercent READ socUsedPercent WRITE qmlWriteSocUsedPercent NOTIFY socUsedPercentChanged FINAL)
    Q_PROPERTY(int ecoShare READ ecoShare WRITE qmlWriteEcoShare NOTIFY ecoShareChanged FINAL)
    Q_PROPERTY(int normalShare READ normalShare WRITE qmlWriteNormalShare NOTIFY normalShareChanged FINAL)
    Q_PROPERTY(int sportShare READ sportShare WRITE qmlWriteSportShare NOTIFY sportShareChanged FINAL)
    Q_PROPERTY(bool recorded READ recorded WRITE qmlWriteRecorded NOTIFY recordedChanged FINAL)

public:
    explicit TripDataQml(QObject *parent = nullptr);

    int rideMinutes() const;
    void qmlWriteRideMinutes(int value);
    int socUsedPercent() const;
    void qmlWriteSocUsedPercent(int value);
    int ecoShare() const;
    void qmlWriteEcoShare(int value);
    int normalShare() const;
    void qmlWriteNormalShare(int value);
    int sportShare() const;
    void qmlWriteSportShare(int value);
    bool recorded() const;
    void qmlWriteRecorded(bool value);
    Q_INVOKABLE void reset();

signals:
    void rideMinutesChanged();
    void socUsedPercentChanged();
    void ecoShareChanged();
    void normalShareChanged();
    void sportShareChanged();
    void recordedChanged();
};

class VehicleDataQml : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(VehicleData)
    QML_SINGLETON
    Q_PROPERTY(int speedKmh READ speedKmh WRITE qmlWriteSpeedKmh NOTIFY speedKmhChanged FINAL)
    Q_PROPERTY(int motorRpm READ motorRpm WRITE qmlWriteMotorRpm NOTIFY motorRpmChanged FINAL)
    Q_PROPERTY(int powerPercent READ powerPercent WRITE qmlWritePowerPercent NOTIFY powerPercentChanged FINAL)
    Q_PROPERTY(int rideMode READ rideMode WRITE qmlWriteRideMode NOTIFY rideModeChanged FINAL)
    Q_PROPERTY(int driveState READ driveState WRITE qmlWriteDriveState NOTIFY driveStateChanged FINAL)
    Q_PROPERTY(bool readyToRide READ readyToRide WRITE qmlWriteReadyToRide NOTIFY readyToRideChanged FINAL)
    Q_PROPERTY(bool sideStandDown READ sideStandDown WRITE qmlWriteSideStandDown NOTIFY sideStandDownChanged FINAL)
    Q_PROPERTY(int batteryPercent READ batteryPercent WRITE qmlWriteBatteryPercent NOTIFY batteryPercentChanged FINAL)
    Q_PROPERTY(int packVoltageX10 READ packVoltageX10 WRITE qmlWritePackVoltageX10 NOTIFY packVoltageX10Changed FINAL)
    Q_PROPERTY(int packCurrentAx10 READ packCurrentAx10 WRITE qmlWritePackCurrentAx10 NOTIFY packCurrentAx10Changed FINAL)
    Q_PROPERTY(int packTempC READ packTempC WRITE qmlWritePackTempC NOTIFY packTempCChanged FINAL)
    Q_PROPERTY(int motorTempC READ motorTempC WRITE qmlWriteMotorTempC NOTIFY motorTempCChanged FINAL)
    Q_PROPERTY(int controllerTempC READ controllerTempC WRITE qmlWriteControllerTempC NOTIFY controllerTempCChanged FINAL)
    Q_PROPERTY(int ambientTempC READ ambientTempC WRITE qmlWriteAmbientTempC NOTIFY ambientTempCChanged FINAL)
    Q_PROPERTY(int chargeState READ chargeState WRITE qmlWriteChargeState NOTIFY chargeStateChanged FINAL)
    Q_PROPERTY(int rangeKm READ rangeKm WRITE qmlWriteRangeKm NOTIFY rangeKmChanged FINAL)
    Q_PROPERTY(bool indicatorLeft READ indicatorLeft WRITE qmlWriteIndicatorLeft NOTIFY indicatorLeftChanged FINAL)
    Q_PROPERTY(bool indicatorRight READ indicatorRight WRITE qmlWriteIndicatorRight NOTIFY indicatorRightChanged FINAL)
    Q_PROPERTY(bool highBeam READ highBeam WRITE qmlWriteHighBeam NOTIFY highBeamChanged FINAL)
    Q_PROPERTY(bool lowBeam READ lowBeam WRITE qmlWriteLowBeam NOTIFY lowBeamChanged FINAL)
    Q_PROPERTY(bool hazard READ hazard WRITE qmlWriteHazard NOTIFY hazardChanged FINAL)
    Q_PROPERTY(bool absFault READ absFault WRITE qmlWriteAbsFault NOTIFY absFaultChanged FINAL)
    Q_PROPERTY(bool absActive READ absActive WRITE qmlWriteAbsActive NOTIFY absActiveChanged FINAL)
    Q_PROPERTY(int tyreFrontPsiX10 READ tyreFrontPsiX10 WRITE qmlWriteTyreFrontPsiX10 NOTIFY tyreFrontPsiX10Changed FINAL)
    Q_PROPERTY(int tyreRearPsiX10 READ tyreRearPsiX10 WRITE qmlWriteTyreRearPsiX10 NOTIFY tyreRearPsiX10Changed FINAL)
    Q_PROPERTY(int odometerKm READ odometerKm WRITE qmlWriteOdometerKm NOTIFY odometerKmChanged FINAL)
    Q_PROPERTY(int tripKmX10 READ tripKmX10 WRITE qmlWriteTripKmX10 NOTIFY tripKmX10Changed FINAL)
    Q_PROPERTY(int faultCode READ faultCode WRITE qmlWriteFaultCode NOTIFY faultCodeChanged FINAL)
    Q_PROPERTY(bool crashDetected READ crashDetected WRITE qmlWriteCrashDetected NOTIFY crashDetectedChanged FINAL)
    Q_PROPERTY(bool driveStale READ driveStale WRITE qmlWriteDriveStale NOTIFY driveStaleChanged FINAL)
    Q_PROPERTY(bool batteryStale READ batteryStale WRITE qmlWriteBatteryStale NOTIFY batteryStaleChanged FINAL)
    Q_PROPERTY(bool lampsStale READ lampsStale WRITE qmlWriteLampsStale NOTIFY lampsStaleChanged FINAL)

public:
    enum RideMode { Eco = 0, Normal = 1, Sport = 2 };
    Q_ENUM(RideMode)
    enum DriveState { Park = 0, Reverse = 1, Neutral = 2, Drive = 3 };
    Q_ENUM(DriveState)
    enum ChargeState { NotCharging = 0, Charging = 1, ChargeComplete = 2, ChargeFault = 3 };
    Q_ENUM(ChargeState)
    explicit VehicleDataQml(QObject *parent = nullptr);

    int speedKmh() const;
    void qmlWriteSpeedKmh(int value);
    int motorRpm() const;
    void qmlWriteMotorRpm(int value);
    int powerPercent() const;
    void qmlWritePowerPercent(int value);
    int rideMode() const;
    void qmlWriteRideMode(int value);
    int driveState() const;
    void qmlWriteDriveState(int value);
    bool readyToRide() const;
    void qmlWriteReadyToRide(bool value);
    bool sideStandDown() const;
    void qmlWriteSideStandDown(bool value);
    int batteryPercent() const;
    void qmlWriteBatteryPercent(int value);
    int packVoltageX10() const;
    void qmlWritePackVoltageX10(int value);
    int packCurrentAx10() const;
    void qmlWritePackCurrentAx10(int value);
    int packTempC() const;
    void qmlWritePackTempC(int value);
    int motorTempC() const;
    void qmlWriteMotorTempC(int value);
    int controllerTempC() const;
    void qmlWriteControllerTempC(int value);
    int ambientTempC() const;
    void qmlWriteAmbientTempC(int value);
    int chargeState() const;
    void qmlWriteChargeState(int value);
    int rangeKm() const;
    void qmlWriteRangeKm(int value);
    bool indicatorLeft() const;
    void qmlWriteIndicatorLeft(bool value);
    bool indicatorRight() const;
    void qmlWriteIndicatorRight(bool value);
    bool highBeam() const;
    void qmlWriteHighBeam(bool value);
    bool lowBeam() const;
    void qmlWriteLowBeam(bool value);
    bool hazard() const;
    void qmlWriteHazard(bool value);
    bool absFault() const;
    void qmlWriteAbsFault(bool value);
    bool absActive() const;
    void qmlWriteAbsActive(bool value);
    int tyreFrontPsiX10() const;
    void qmlWriteTyreFrontPsiX10(int value);
    int tyreRearPsiX10() const;
    void qmlWriteTyreRearPsiX10(int value);
    int odometerKm() const;
    void qmlWriteOdometerKm(int value);
    int tripKmX10() const;
    void qmlWriteTripKmX10(int value);
    int faultCode() const;
    void qmlWriteFaultCode(int value);
    bool crashDetected() const;
    void qmlWriteCrashDetected(bool value);
    bool driveStale() const;
    void qmlWriteDriveStale(bool value);
    bool batteryStale() const;
    void qmlWriteBatteryStale(bool value);
    bool lampsStale() const;
    void qmlWriteLampsStale(bool value);
    Q_INVOKABLE void applySignal(int signalId, int value);

signals:
    void speedKmhChanged();
    void motorRpmChanged();
    void powerPercentChanged();
    void rideModeChanged();
    void driveStateChanged();
    void readyToRideChanged();
    void sideStandDownChanged();
    void batteryPercentChanged();
    void packVoltageX10Changed();
    void packCurrentAx10Changed();
    void packTempCChanged();
    void motorTempCChanged();
    void controllerTempCChanged();
    void ambientTempCChanged();
    void chargeStateChanged();
    void rangeKmChanged();
    void indicatorLeftChanged();
    void indicatorRightChanged();
    void highBeamChanged();
    void lowBeamChanged();
    void hazardChanged();
    void absFaultChanged();
    void absActiveChanged();
    void tyreFrontPsiX10Changed();
    void tyreRearPsiX10Changed();
    void odometerKmChanged();
    void tripKmX10Changed();
    void faultCodeChanged();
    void crashDetectedChanged();
    void driveStaleChanged();
    void batteryStaleChanged();
    void lampsStaleChanged();
};
