// Generated by tools/generate_cluster_art.py. Do not edit.
import QtQuick
import QtQuickUltralite.Extras

// Tall battery column (hex view): 20 slanted slices, slice 0 at the bottom.
Item {
    id: column

    property int percent: 0
    property int litCount: Math.round(Math.max(0, Math.min(100, percent)) * 20 / 100)
    property color litColor: "#78F0C8"
    property color offColor: "#7E9E93"

    width: 1280
    height: 480

    ColorizedImage {
        source: "qrc:/assets/cluster/battery_tall.png"
        color: column.offColor
    }

    ColorizedImage {
        x: 317
        y: 392
        source: "qrc:/assets/cluster/battery_slice0.png"
        visible: column.litCount > 0
        color: column.litColor
    }

    ColorizedImage {
        x: 298
        y: 383
        source: "qrc:/assets/cluster/battery_slice1.png"
        visible: column.litCount > 1
        color: column.litColor
    }

    ColorizedImage {
        x: 280
        y: 374
        source: "qrc:/assets/cluster/battery_slice2.png"
        visible: column.litCount > 2
        color: column.litColor
    }

    ColorizedImage {
        x: 262
        y: 365
        source: "qrc:/assets/cluster/battery_slice3.png"
        visible: column.litCount > 3
        color: column.litColor
    }

    ColorizedImage {
        x: 244
        y: 355
        source: "qrc:/assets/cluster/battery_slice4.png"
        visible: column.litCount > 4
        color: column.litColor
    }

    ColorizedImage {
        x: 226
        y: 346
        source: "qrc:/assets/cluster/battery_slice5.png"
        visible: column.litCount > 5
        color: column.litColor
    }

    ColorizedImage {
        x: 207
        y: 336
        source: "qrc:/assets/cluster/battery_slice6.png"
        visible: column.litCount > 6
        color: column.litColor
    }

    ColorizedImage {
        x: 190
        y: 325
        source: "qrc:/assets/cluster/battery_slice7.png"
        visible: column.litCount > 7
        color: column.litColor
    }

    ColorizedImage {
        x: 177
        y: 311
        source: "qrc:/assets/cluster/battery_slice8.png"
        visible: column.litCount > 8
        color: column.litColor
    }

    ColorizedImage {
        x: 169
        y: 292
        source: "qrc:/assets/cluster/battery_slice9.png"
        visible: column.litCount > 9
        color: column.litColor
    }

    ColorizedImage {
        x: 163
        y: 272
        source: "qrc:/assets/cluster/battery_slice10.png"
        visible: column.litCount > 10
        color: column.litColor
    }

    ColorizedImage {
        x: 156
        y: 252
        source: "qrc:/assets/cluster/battery_slice11.png"
        visible: column.litCount > 11
        color: column.litColor
    }

    ColorizedImage {
        x: 150
        y: 233
        source: "qrc:/assets/cluster/battery_slice12.png"
        visible: column.litCount > 12
        color: column.litColor
    }

    ColorizedImage {
        x: 144
        y: 213
        source: "qrc:/assets/cluster/battery_slice13.png"
        visible: column.litCount > 13
        color: column.litColor
    }

    ColorizedImage {
        x: 137
        y: 193
        source: "qrc:/assets/cluster/battery_slice14.png"
        visible: column.litCount > 14
        color: column.litColor
    }

    ColorizedImage {
        x: 131
        y: 173
        source: "qrc:/assets/cluster/battery_slice15.png"
        visible: column.litCount > 15
        color: column.litColor
    }

    ColorizedImage {
        x: 124
        y: 152
        source: "qrc:/assets/cluster/battery_slice16.png"
        visible: column.litCount > 16
        color: column.litColor
    }

    ColorizedImage {
        x: 118
        y: 132
        source: "qrc:/assets/cluster/battery_slice17.png"
        visible: column.litCount > 17
        color: column.litColor
    }

    ColorizedImage {
        x: 113
        y: 111
        source: "qrc:/assets/cluster/battery_slice18.png"
        visible: column.litCount > 18
        color: column.litColor
    }

    ColorizedImage {
        x: 116
        y: 104
        source: "qrc:/assets/cluster/battery_slice19.png"
        visible: column.litCount > 19
        color: column.litColor
    }
}
