// Generated by tools/generate_cluster_art.py. Do not edit.
import QtQuick
import QtQuickUltralite.Extras

// Tall battery column (hex view): 20 slanted slices, slice 0 at the bottom.
Item {
    id: column

    property int percent: 0
    property int litCount: Math.round(Math.max(0, Math.min(100, percent)) * 20 / 100)
    property color litColor: "#78F0C8"
    property color offColor: "#7E9E93"

    width: 1280
    height: 480

    ColorizedImage {
        source: "qrc:/assets/cluster/battery_tall.png"
        color: column.offColor
    }

    ColorizedImage {
        x: 318
        y: 393
        source: "qrc:/assets/cluster/battery_slice0.png"
        visible: column.litCount > 0
        color: column.litColor
    }

    ColorizedImage {
        x: 299
        y: 384
        source: "qrc:/assets/cluster/battery_slice1.png"
        visible: column.litCount > 1
        color: column.litColor
    }

    ColorizedImage {
        x: 282
        y: 375
        source: "qrc:/assets/cluster/battery_slice2.png"
        visible: column.litCount > 2
        color: column.litColor
    }

    ColorizedImage {
        x: 263
        y: 365
        source: "qrc:/assets/cluster/battery_slice3.png"
        visible: column.litCount > 3
        color: column.litColor
    }

    ColorizedImage {
        x: 246
        y: 356
        source: "qrc:/assets/cluster/battery_slice4.png"
        visible: column.litCount > 4
        color: column.litColor
    }

    ColorizedImage {
        x: 228
        y: 347
        source: "qrc:/assets/cluster/battery_slice5.png"
        visible: column.litCount > 5
        color: column.litColor
    }

    ColorizedImage {
        x: 210
        y: 337
        source: "qrc:/assets/cluster/battery_slice6.png"
        visible: column.litCount > 6
        color: column.litColor
    }

    ColorizedImage {
        x: 192
        y: 327
        source: "qrc:/assets/cluster/battery_slice7.png"
        visible: column.litCount > 7
        color: column.litColor
    }

    ColorizedImage {
        x: 179
        y: 313
        source: "qrc:/assets/cluster/battery_slice8.png"
        visible: column.litCount > 8
        color: column.litColor
    }

    ColorizedImage {
        x: 170
        y: 296
        source: "qrc:/assets/cluster/battery_slice9.png"
        visible: column.litCount > 9
        color: column.litColor
    }

    ColorizedImage {
        x: 164
        y: 276
        source: "qrc:/assets/cluster/battery_slice10.png"
        visible: column.litCount > 10
        color: column.litColor
    }

    ColorizedImage {
        x: 158
        y: 257
        source: "qrc:/assets/cluster/battery_slice11.png"
        visible: column.litCount > 11
        color: column.litColor
    }

    ColorizedImage {
        x: 152
        y: 238
        source: "qrc:/assets/cluster/battery_slice12.png"
        visible: column.litCount > 12
        color: column.litColor
    }

    ColorizedImage {
        x: 145
        y: 218
        source: "qrc:/assets/cluster/battery_slice13.png"
        visible: column.litCount > 13
        color: column.litColor
    }

    ColorizedImage {
        x: 139
        y: 199
        source: "qrc:/assets/cluster/battery_slice14.png"
        visible: column.litCount > 14
        color: column.litColor
    }

    ColorizedImage {
        x: 133
        y: 179
        source: "qrc:/assets/cluster/battery_slice15.png"
        visible: column.litCount > 15
        color: column.litColor
    }

    ColorizedImage {
        x: 127
        y: 159
        source: "qrc:/assets/cluster/battery_slice16.png"
        visible: column.litCount > 16
        color: column.litColor
    }

    ColorizedImage {
        x: 120
        y: 139
        source: "qrc:/assets/cluster/battery_slice17.png"
        visible: column.litCount > 17
        color: column.litColor
    }

    ColorizedImage {
        x: 115
        y: 118
        source: "qrc:/assets/cluster/battery_slice18.png"
        visible: column.litCount > 18
        color: column.litColor
    }

    ColorizedImage {
        x: 113
        y: 104
        source: "qrc:/assets/cluster/battery_slice19.png"
        visible: column.litCount > 19
        color: column.litColor
    }
}
