// Generated by tools/generate_cluster_art.py. Do not edit.
import QtQuick
import QtQuickUltralite.Extras
import ClusterCore

// Hexagon speedometer: 10 segments (two halves each), labels 0..140 and needle.
Item {
    id: gauge

    property int speed: 0
    property int clamped: Math.max(0, Math.min(150, speed))
    property bool stale: false
    property bool miles: false

    // The printed scale is calibrated in km/h. In miles the same tick
    // carries the same speed in the rider's unit, so the numbers and
    // the needle still agree.
    function labelText(kmh: int) : string {
        return miles ? "" + Math.round(kmh * 0.621371) : "" + kmh
    }

    property color litColor: "#7DFFDB"
    property color offColor: "#3C3C3D"
    readonly property real targetNeedleAngle: (clamped < 20 ? 160.2 + (clamped - 0) * 1.543 : (clamped < 40 ? 191.1 + (clamped - 20) * 1.306 : (clamped < 60 ? 217.2 + (clamped - 40) * 1.896 : (clamped < 80 ? 255.1 + (clamped - 60) * 1.726 : (clamped < 100 ? 289.7 + (clamped - 80) * 1.631 : (clamped < 120 ? 322.3 + (clamped - 100) * 1.321 : (clamped < 140 ? 348.7 + (clamped - 120) * 1.395 : 376.6)))))))

    // Animate an assigned value, avoiding the bound-property animation loop.
    property real needleAngle: 160.2
    onTargetNeedleAngleChanged: needleAngle = targetNeedleAngle
    Component.onCompleted: needleAngle = targetNeedleAngle
    Behavior on needleAngle {
        NumberAnimation { duration: 100; easing.type: Easing.Linear }
    }

    x: 440
    y: 70
    width: 420
    height: 290

    ColorizedImage {
        x: 90
        y: 210
        source: "qrc:/assets/cluster/hex_piece0.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 68
        y: 188
        source: "qrc:/assets/cluster/hex_piece1.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 46
        y: 165
        source: "qrc:/assets/cluster/hex_piece2.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 25
        y: 135
        source: "qrc:/assets/cluster/hex_piece3.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 25
        y: 104
        source: "qrc:/assets/cluster/hex_piece4.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 46
        y: 72
        source: "qrc:/assets/cluster/hex_piece5.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 68
        y: 41
        source: "qrc:/assets/cluster/hex_piece6.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 90
        y: 11
        source: "qrc:/assets/cluster/hex_piece7.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 112
        y: 11
        source: "qrc:/assets/cluster/hex_piece8.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 156
        y: 11
        source: "qrc:/assets/cluster/hex_piece9.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 201
        y: 11
        source: "qrc:/assets/cluster/hex_piece10.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 234
        y: 11
        source: "qrc:/assets/cluster/hex_piece11.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 265
        y: 11
        source: "qrc:/assets/cluster/hex_piece12.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 281
        y: 41
        source: "qrc:/assets/cluster/hex_piece13.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 297
        y: 72
        source: "qrc:/assets/cluster/hex_piece14.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 313
        y: 104
        source: "qrc:/assets/cluster/hex_piece15.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 302
        y: 135
        source: "qrc:/assets/cluster/hex_piece16.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 286
        y: 165
        source: "qrc:/assets/cluster/hex_piece17.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 270
        y: 188
        source: "qrc:/assets/cluster/hex_piece18.png"
        color: gauge.offColor
    }

    ColorizedImage {
        x: 255
        y: 210
        source: "qrc:/assets/cluster/hex_piece19.png"
        color: gauge.offColor
    }

    HexGaugeFill {
        angle: gauge.needleAngle
        color: gauge.litColor
        visible: !gauge.stale
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_shade.png"
        color: "#000000"
        opacity: 0.35
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_rim.png"
        color: "#FFFFFF"
        opacity: 0.08
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_dividers.png"
        color: "#0A0B0C"
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_inner.png"
        color: Theme.hexRing
    }

    Text {
        x: 72
        y: 165
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(0)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 56
        y: 101
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(20)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 90
        y: 56
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(40)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 155
        y: 27
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(60)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 216
        y: 27
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(80)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 276
        y: 52
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(100)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 311
        y: 99
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(120)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    Text {
        x: 304
        y: 162
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: gauge.labelText(140)
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 18
        font.italic: true
    }

    // An image, not a Rectangle: Qt for MCUs only transforms Image, Text and
    // StaticText. The old gradient is the alpha ramp baked into the art.
    ColorizedImage {
        x: 205.0
        y: 136.0
        width: 132
        height: 5
        visible: !gauge.stale
        source: "qrc:/assets/cluster/needle_amp.png"
        color: "#E8141E"
        transform: Rotation {
            origin.x: 0
            origin.y: 2.5
            angle: gauge.needleAngle
        }
    }
}
