// Generated by tools/generate_cluster_art.py. Do not edit.
import QtQuick
import QtQuickUltralite.Extras
import ClusterCore

// Hexagon speedometer: 10 segments (two halves each), labels 0..140 and needle.
Item {
    id: gauge

    property int speed: 0
    property int clamped: Math.max(0, Math.min(150, speed))
    property int litHalves: Math.round(3 + clamped / 10)
    property color litColor: "#5FE8BE"
    property color offColor: "#3A3D40"
    property real needleAngle: (clamped < 20 ? 160.6 + (clamped - 0) * 1.512 : (clamped < 40 ? 190.9 + (clamped - 20) * 1.280 : (clamped < 60 ? 216.5 + (clamped - 40) * 1.865 : (clamped < 80 ? 253.8 + (clamped - 60) * 1.728 : (clamped < 100 ? 288.3 + (clamped - 80) * 1.659 : (clamped < 120 ? 321.5 + (clamped - 100) * 1.347 : (clamped < 140 ? 348.5 + (clamped - 120) * 1.422 : 376.9)))))))

    x: 440
    y: 70
    width: 420
    height: 290

    ColorizedImage {
        x: 92
        y: 213
        source: "qrc:/assets/cluster/hex_piece0.png"
        color: gauge.litHalves > 0 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 70
        y: 189
        source: "qrc:/assets/cluster/hex_piece1.png"
        color: gauge.litHalves > 1 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 48
        y: 166
        source: "qrc:/assets/cluster/hex_piece2.png"
        color: gauge.litHalves > 2 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 27
        y: 135
        source: "qrc:/assets/cluster/hex_piece3.png"
        color: gauge.litHalves > 3 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 27
        y: 104
        source: "qrc:/assets/cluster/hex_piece4.png"
        color: gauge.litHalves > 4 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 48
        y: 72
        source: "qrc:/assets/cluster/hex_piece5.png"
        color: gauge.litHalves > 5 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 70
        y: 41
        source: "qrc:/assets/cluster/hex_piece6.png"
        color: gauge.litHalves > 6 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 92
        y: 11
        source: "qrc:/assets/cluster/hex_piece7.png"
        color: gauge.litHalves > 7 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 114
        y: 11
        source: "qrc:/assets/cluster/hex_piece8.png"
        color: gauge.litHalves > 8 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 158
        y: 11
        source: "qrc:/assets/cluster/hex_piece9.png"
        color: gauge.litHalves > 9 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 203
        y: 11
        source: "qrc:/assets/cluster/hex_piece10.png"
        color: gauge.litHalves > 10 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 239
        y: 11
        source: "qrc:/assets/cluster/hex_piece11.png"
        color: gauge.litHalves > 11 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 275
        y: 11
        source: "qrc:/assets/cluster/hex_piece12.png"
        color: gauge.litHalves > 12 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 294
        y: 41
        source: "qrc:/assets/cluster/hex_piece13.png"
        color: gauge.litHalves > 13 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 312
        y: 72
        source: "qrc:/assets/cluster/hex_piece14.png"
        color: gauge.litHalves > 14 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 330
        y: 104
        source: "qrc:/assets/cluster/hex_piece15.png"
        color: gauge.litHalves > 15 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 318
        y: 135
        source: "qrc:/assets/cluster/hex_piece16.png"
        color: gauge.litHalves > 16 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 299
        y: 166
        source: "qrc:/assets/cluster/hex_piece17.png"
        color: gauge.litHalves > 17 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 280
        y: 189
        source: "qrc:/assets/cluster/hex_piece18.png"
        color: gauge.litHalves > 18 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        x: 262
        y: 213
        source: "qrc:/assets/cluster/hex_piece19.png"
        color: gauge.litHalves > 19 ? gauge.litColor : gauge.offColor
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_shade.png"
        color: "#FFFFFF"
        opacity: 0.16
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_dividers.png"
        color: "#0A0B0C"
    }

    ColorizedImage {
        source: "qrc:/assets/cluster/hex_inner.png"
        color: Theme.teal
    }

    Text {
        x: 72
        y: 165
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "0"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 56
        y: 101
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "20"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 90
        y: 56
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "40"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 155
        y: 27
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "60"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 216
        y: 27
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "80"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 276
        y: 52
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "100"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 311
        y: 99
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "120"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Text {
        x: 304
        y: 162
        width: 48
        horizontalAlignment: Text.AlignHCenter
        text: "140"
        color: "#EEF1F1"
        font.family: Theme.fontFamily
        font.pixelSize: 20
        font.italic: true
    }

    Rectangle {
        x: 207.5
        y: 136.5
        width: 132
        height: 4
        radius: 2
        gradient: Gradient {
            orientation: Gradient.Horizontal
            GradientStop { position: 0.0; color: "#40E0303A" }
            GradientStop { position: 1.0; color: "#E8202C" }
        }
        transform: Rotation {
            origin.x: 0
            origin.y: 2
            angle: gauge.needleAngle
        }
    }
}
