// Generated by tools/generate_cluster_art.py. Do not edit.
import QtQuick
import QtQuickUltralite.Extras
import ClusterCore

// Right RPM bar. Segment 0 is at the bottom.
Item {
    id: bar

    property int value: 0
    property int litCount: Math.round(Math.max(0, Math.min(100, value)) * 8 / 100)
    property color lowColor: Theme.segLow
    property color highColor: Theme.segHigh
    property color topColor: Theme.segTop
    property color offColor: Theme.segOff
    property bool redZoneTop: false

    width: 1280
    height: 480

    function segColor(fraction: real) : color {
        return Qt.rgba(lowColor.r + (highColor.r - lowColor.r) * fraction,
                       lowColor.g + (highColor.g - lowColor.g) * fraction,
                       lowColor.b + (highColor.b - lowColor.b) * fraction, 1)
    }

    ColorizedImage {
        x: 906
        y: 383
        source: "qrc:/assets/cluster/seg_r0.png"
        color: bar.litCount > 0 ? bar.segColor(0.00) : bar.offColor
    }

    ColorizedImage {
        x: 948
        y: 361
        source: "qrc:/assets/cluster/seg_r1.png"
        color: bar.litCount > 1 ? bar.segColor(0.17) : bar.offColor
    }

    ColorizedImage {
        x: 991
        y: 339
        source: "qrc:/assets/cluster/seg_r2.png"
        color: bar.litCount > 2 ? bar.segColor(0.33) : bar.offColor
    }

    ColorizedImage {
        x: 1033
        y: 307
        source: "qrc:/assets/cluster/seg_r3.png"
        color: bar.litCount > 3 ? bar.segColor(0.50) : bar.offColor
    }

    ColorizedImage {
        x: 1070
        y: 253
        source: "qrc:/assets/cluster/seg_r4.png"
        color: bar.litCount > 4 ? bar.segColor(0.67) : bar.offColor
    }

    ColorizedImage {
        x: 1088
        y: 200
        source: "qrc:/assets/cluster/seg_r5.png"
        color: bar.litCount > 5 ? bar.segColor(0.83) : bar.offColor
    }

    ColorizedImage {
        x: 1106
        y: 148
        source: "qrc:/assets/cluster/seg_r6.png"
        color: bar.litCount > 6 ? bar.segColor(1.00) : bar.offColor
    }

    ColorizedImage {
        x: 1124
        y: 98
        source: "qrc:/assets/cluster/seg_r7.png"
        color: bar.redZoneTop ? Theme.segRedZone : (bar.litCount >= 8 ? bar.topColor : bar.offColor)
    }

    Text {
        x: 1117
        y: 131
        width: 60
        horizontalAlignment: Text.AlignHCenter
        text: "× 8"
        color: Theme.textPrimary
        font.family: Theme.fontFamily
        font.pixelSize: 12
        font.bold: true
        font.italic: true
    }

    Text {
        x: 1039
        y: 327
        width: 60
        horizontalAlignment: Text.AlignHCenter
        text: "× 4"
        color: Theme.textPrimary
        font.family: Theme.fontFamily
        font.pixelSize: 12
        font.bold: true
        font.italic: true
    }

    Text {
        x: 916
        y: 399
        width: 60
        horizontalAlignment: Text.AlignHCenter
        text: "RPM"
        color: Theme.textPrimary
        font.family: Theme.fontFamily
        font.pixelSize: 12
        font.bold: true
        font.italic: true
    }
}
