#!/usr/bin/env python3
"""Generates Qt 6 QObject singletons from the Qt for MCUs interface headers.

Desktop (Qt 6) builds cannot use Qul::Singleton directly, so each struct in
qml/backend/*.h gets a QObject twin registered as a QML singleton with the same
name, properties, enums, functions and signals.

Run after changing any header in qml/backend:
    python3 tools/generate_desktop_bridge.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "qml", "backend")
OUT_DIR = os.path.join(ROOT, "desktop", "bridge")

TYPE_MAP = {"int": "int", "bool": "bool", "float": "double", "double": "double", "std::string": "QString"}

STRUCT_RE = re.compile(r"struct\s+(\w+)\s*:\s*public\s+Qul::Singleton<\s*\1\s*>\s*\{(.*?)\n\};", re.S)
PROP_RE = re.compile(r"^\s*Qul::Property<\s*([\w:]+)\s*>\s+(\w+)\s*;", re.M)
SIGNAL_RE = re.compile(r"^\s*Qul::Signal<\s*void\s*\(([^)]*)\)\s*>\s+(\w+)\s*;", re.M)
ENUM_RE = re.compile(r"^\s*enum\s+(\w+)\s*\{(.*?)\};", re.M | re.S)
FUNC_RE = re.compile(r"^\s*(void|bool|int)\s+(\w+)\s*\(([^)]*)\)\s*;", re.M)


def cap(name):
    return name[0].upper() + name[1:]


def parse_args(args):
    args = args.strip()
    if not args:
        return []
    out = []
    for a in args.split(","):
        parts = a.strip().rsplit(" ", 1)
        out.append((parts[0].strip(), parts[1].strip()))
    return out


def parse(path):
    text = open(path, encoding="utf-8").read()
    m = STRUCT_RE.search(text)
    if not m:
        return None
    name, body = m.group(1), m.group(2)
    public = body.split("private:")[0]
    enums = [(e.group(1), " ".join(e.group(2).split())) for e in ENUM_RE.finditer(public)]
    props = [(TYPE_MAP[p.group(1)], p.group(2), p.group(1)) for p in PROP_RE.finditer(public)]
    signals = [(s.group(2), parse_args(s.group(1))) for s in SIGNAL_RE.finditer(public)]
    funcs = [(f.group(1), f.group(2), parse_args(f.group(3))) for f in FUNC_RE.finditer(public)]
    # A function whose arguments the bridge cannot express (a std::string by
    # reference, say) is one the backend calls itself, not one QML calls.
    funcs = [f for f in funcs if all(t in TYPE_MAP for t, _ in f[2])]
    return {"name": name, "header": os.path.basename(path), "enums": enums, "props": props,
            "signals": signals, "funcs": funcs}


def to_qt(qt_type, expr):
    return f"QString::fromStdString({expr})" if qt_type == "QString" else expr


def to_qul(qt_type, expr):
    return f"{expr}.toStdString()" if qt_type == "QString" else expr


def gen_header(classes):
    out = ["// Generated by tools/generate_desktop_bridge.py. Do not edit.", "#pragma once", "",
           "#include <QObject>", "#include <QString>", "#include <QtQml/qqmlregistration.h>", ""]
    for c in classes:
        q = c["name"] + "Qml"
        out += [f"class {q} : public QObject", "{", "    Q_OBJECT", f"    QML_NAMED_ELEMENT({c['name']})",
                "    QML_SINGLETON"]
        for t, n, _ in c["props"]:
            out.append(f"    Q_PROPERTY({t} {n} READ {n} WRITE qmlWrite{cap(n)} NOTIFY {n}Changed FINAL)")
        out += ["", "public:"]
        for en, body in c["enums"]:
            out += [f"    enum {en} {{ {body} }};", f"    Q_ENUM({en})"]
        out += [f"    explicit {q}(QObject *parent = nullptr);", ""]
        for t, n, _ in c["props"]:
            arg = f"const {t} &value" if t == "QString" else f"{t} value"
            out += [f"    {t} {n}() const;", f"    void qmlWrite{cap(n)}({arg});"]
        for ret, n, args in c["funcs"]:
            sig = ", ".join(f"{t} {a}" for t, a in args)
            out.append(f"    Q_INVOKABLE {ret} {n}({sig});")
        out += ["", "signals:"]
        for t, n, _ in c["props"]:
            out.append(f"    void {n}Changed();")
        for n, args in c["signals"]:
            sig = ", ".join(f"{t} {a}" for t, a in args)
            out.append(f"    void {n}({sig});")
        out += ["};", ""]
    return "\n".join(out)


def gen_source(classes):
    out = ["// Generated by tools/generate_desktop_bridge.py. Do not edit.", '#include "QulQmlBridge.h"', ""]
    for c in classes:
        out.append(f'#include "{c["header"]}"')
    out.append("")
    for c in classes:
        q, s = c["name"] + "Qml", c["name"]
        out += [f"{q}::{q}(QObject *parent)", "    : QObject(parent)", "{", f"    {s} &d = {s}::instance();"]
        for t, n, _ in c["props"]:
            out.append(f"    d.{n}.setOnChanged([this] {{ emit {n}Changed(); }});")
        for n, args in c["signals"]:
            params = ", ".join(f"{t} {a}" for t, a in args)
            names = ", ".join(a for _, a in args)
            out.append(f"    d.{n}.connect([this]({params}) {{ emit {n}({names}); }});")
        out += ["}", ""]
        for t, n, _ in c["props"]:
            arg = f"const {t} &value" if t == "QString" else f"{t} value"
            out += [f"{t} {q}::{n}() const", "{", f"    return {to_qt(t, f'{s}::instance().{n}.value()')};", "}", "",
                    f"void {q}::qmlWrite{cap(n)}({arg})", "{",
                    f"    {s}::instance().{n}.setValue({to_qul(t, 'value')});", "}", ""]
        for ret, n, args in c["funcs"]:
            sig = ", ".join(f"{t} {a}" for t, a in args)
            names = ", ".join(a for _, a in args)
            prefix = "return " if ret != "void" else ""
            out += [f"{ret} {q}::{n}({sig})", "{", f"    {prefix}{s}::instance().{n}({names});", "}", ""]
    return "\n".join(out)


def main():
    classes = []
    for f in sorted(os.listdir(SRC_DIR)):
        if f.endswith(".h"):
            c = parse(os.path.join(SRC_DIR, f))
            if c:
                classes.append(c)
    os.makedirs(OUT_DIR, exist_ok=True)
    open(os.path.join(OUT_DIR, "QulQmlBridge.h"), "w").write(gen_header(classes))
    open(os.path.join(OUT_DIR, "QulQmlBridge.cpp"), "w").write(gen_source(classes))
    for c in classes:
        print(f"{c['name']}: {len(c['props'])} props, {len(c['enums'])} enums, "
              f"{len(c['funcs'])} funcs, {len(c['signals'])} signals")


if __name__ == "__main__":
    main()
