#!/usr/bin/env python3
"""Keeps the file lists of both builds in sync with the folders.

Rewrites:
  qml/core|components|screens/*.qmlproject   (Qt for MCUs)
  qml/core|components|screens/CMakeLists.txt (Qt 6 desktop)
  EVBikes.qmlproject                         (images and fonts)
Run after adding or removing a QML file or an image:
    python3 tools/sync_project_files.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MODULES = {
    "core": ("ClusterCore", "cluster_core", ["Theme.qml", "Router.qml", "Format.qml"]),
    "components": ("ClusterComponents", "cluster_components", []),
    "screens": ("ClusterScreens", "cluster_screens", []),
}

# Colour artwork (not tinted) keeps its RGB channels.
COLOUR_IMAGES = {"payment_card.png", "album_art.png", "seat.png"}


def qml_files(folder, singletons):
    files = sorted(f for f in os.listdir(folder) if f.endswith(".qml"))
    return singletons + [f for f in files if f not in singletons]


def write_module(name, uri, target, singletons):
    folder = os.path.join(ROOT, "qml", name)
    files = qml_files(folder, singletons)
    listing = ",\n".join(f'            "{f}"' for f in files)
    with open(os.path.join(folder, f"{name}.qmlproject"), "w") as fh:
        fh.write(f"""import QmlProject 1.3

Project {{
    MCU.Module {{
        uri: "{uri}"
    }}

    QmlFiles {{
        files: [
{listing}
        ]
    }}
}}
""")
    cm = [f"# Qt 6 desktop build only (the MCU build uses {name}.qmlproject).",
          "# Generated by tools/sync_project_files.py."]
    if singletons:
        cm.append(f"set_source_files_properties({' '.join(singletons)} PROPERTIES QT_QML_SINGLETON_TYPE TRUE)")
        cm.append("")
    cm += [f"qt_add_library({target} STATIC)",
           f"qt_add_qml_module({target}",
           f"    URI {uri}",
           "    VERSION 1.0",
           f"    OUTPUT_DIRECTORY ${{EVB_QML_OUT}}/{uri}",
           "    QML_FILES"]
    cm += [f"        {f}" for f in files]
    cm.append(")")
    with open(os.path.join(folder, "CMakeLists.txt"), "w") as fh:
        fh.write("\n".join(cm) + "\n")
    return len(files)


def image_list(sub, predicate=lambda f: True):
    base = os.path.join(ROOT, "assets", sub)
    found = []
    for folder, _, files in os.walk(base):
        rel = os.path.relpath(folder, base)
        for f in files:
            if f.endswith(".png") and predicate(f):
                found.append(f"assets/{sub}/{f}" if rel == "." else f"assets/{sub}/{rel}/{f}")
    return sorted(found, key=lambda p: [int(t) if t.isdigit() else t for t in p.split("/")])


def block(files):
    return ",\n".join(f'            "{f}"' for f in files)


def write_main_project():
    tinted = image_list("icons") + image_list("turns") + image_list("images") + \
        image_list("cluster", lambda f: f not in COLOUR_IMAGES and not f.startswith("bike_") or f.endswith(("_rear.png", "_wheel.png")))
    colour = image_list("cluster", lambda f: f in COLOUR_IMAGES or (f.startswith("bike_") and not f.endswith(("_rear.png", "_wheel.png"))))
    fonts = [f"assets/fonts/{f}" for f in sorted(os.listdir(os.path.join(ROOT, "assets", "fonts"))) if f.endswith(".ttf")]
    text = f"""import QmlProject 1.3

// Generated by tools/sync_project_files.py.
Project {{
    mainFile: "qml/Main.qml"
    qtForMCUs: true
    projectRootPath: "."

    MCU.Config {{
        fontEngine: "Static"
        defaultFontFamily: "Inter"
        addDefaultFonts: false
        autoGenerateGlyphs: true
        mergeStaticTextGlyphs: true
    }}

    QmlFiles {{
        files: [
            "qml/Main.qml"
        ]
    }}

    ModuleFiles {{
        files: [
            "qml/backend/backend.qmlproject",
            "qml/core/core.qmlproject",
            "qml/components/components.qmlproject",
            "qml/screens/screens.qmlproject"
        ]
        MCU.qulModules: ["Shapes"]
    }}

    // White artwork tinted with ColorizedImage: only the alpha channel is stored.
    ImageFiles {{
        files: [
{block(tinted)}
        ]
        MCU.resourceImagePixelFormat: "Alpha8"
        MCU.resourceCompression: true
    }}

    // Colour artwork.
    ImageFiles {{
        files: [
{block(colour)}
        ]
        MCU.resourceImagePixelFormat: "Automatic"
        MCU.resourceCompression: true
    }}

    FontFiles {{
        files: [
{block(fonts)}
        ]
    }}
}}
"""
    with open(os.path.join(ROOT, "EVBikes.qmlproject"), "w") as fh:
        fh.write(text)
    return len(tinted), len(colour)


def main():
    for name, (uri, target, singletons) in MODULES.items():
        print(name, write_module(name, uri, target, singletons), "qml files")
    print("images (alpha, colour):", write_main_project())


if __name__ == "__main__":
    main()
