#!/usr/bin/env python3
"""Keeps the file lists of both builds in sync with the folders.

Rewrites:
  qml/core|components|screens/*.qmlproject   (Qt for MCUs)
  qml/core|components|screens/CMakeLists.txt (Qt 6 desktop)
  EVBikes.qmlproject                         (images and fonts)
Run after adding or removing a QML file or an image:
    python3 tools/sync_project_files.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# name: (uri, cmake target, singletons, modules this one imports, Qul modules)
# Qt for MCUs resolves a module import against the importing project's own
# ModuleFiles, not the root's, so every module has to name what it imports.
MODULES = {
    "core": ("ClusterCore", "cluster_core", ["Theme.qml", "Router.qml", "Format.qml"],
             ["backend"], []),
    "components": ("ClusterComponents", "cluster_components", [],
                   ["backend", "core"], []),
    "screens": ("ClusterScreens", "cluster_screens", [],
                ["backend", "core", "components"], ["Shapes"]),
}

# Colour artwork (not tinted) keeps its RGB channels.
COLOUR_IMAGES = {"payment_card.png", "album_art.png", "seat.png"}


def qml_files(folder, singletons):
    files = sorted(f for f in os.listdir(folder) if f.endswith(".qml"))
    return singletons + [f for f in files if f not in singletons]


def module_images(folder):
    """The qrc: images this module's own QML names, as paths from the module."""
    found = set()
    for f in os.listdir(folder):
        if not f.endswith(".qml"):
            continue
        with open(os.path.join(folder, f), encoding="utf-8") as fh:
            found.update(re.findall(r'"qrc:/([^"]+\.png)"', fh.read()))
    tinted = sorted(p for p in found if os.path.basename(p) not in COLOUR_IMAGES)
    colour = sorted(p for p in found if os.path.basename(p) in COLOUR_IMAGES)
    return tinted, colour


def write_module(name, uri, target, singletons, imports, qul_modules):
    folder = os.path.join(ROOT, "qml", name)
    files = qml_files(folder, singletons)
    listing = ",\n".join(f'            "qml/{name}/{f}"' for f in files)
    deps = ""
    if imports or qul_modules:
        dep_list = ",\n".join(f'            "qml/{d}/{d}.qmlproject"' for d in imports)
        quls = ""
        if qul_modules:
            names = ", ".join(f'"{m}"' for m in qul_modules)
            quls = f"\n        MCU.qulModules: [{names}]"
        deps = f"""
    ModuleFiles {{
        files: [
{dep_list}
        ]{quls}
    }}
"""
    tinted, colour = module_images(folder)
    images = ""
    for group, fmt in ((tinted, "Alpha8"), (colour, "Automatic")):
        if not group:
            continue
        rows = ",\n".join(f'            "{f}"' for f in group)
        images += f"""
    ImageFiles {{
        files: [
{rows}
        ]
        MCU.resourceImagePixelFormat: "{fmt}"
        MCU.resourceCompression: true
    }}
"""
    with open(os.path.join(folder, f"{name}.qmlproject"), "w") as fh:
        fh.write(f"""import QmlProject 1.3

Project {{
    projectRootPath: "../.."

    MCU.Module {{
        uri: "{uri}"
    }}
{deps}{images}
    QmlFiles {{
        files: [
{listing}
        ]
    }}
}}
""")
    cm = [f"# Qt 6 desktop build only (the MCU build uses {name}.qmlproject).",
          "# Generated by tools/sync_project_files.py."]
    if singletons:
        cm.append(f"set_source_files_properties({' '.join(singletons)} PROPERTIES QT_QML_SINGLETON_TYPE TRUE)")
        cm.append("")
    cm += [f"qt_add_library({target} STATIC)",
           f"qt_add_qml_module({target}",
           f"    URI {uri}",
           "    VERSION 1.0",
           f"    OUTPUT_DIRECTORY ${{EVB_QML_OUT}}/{uri}",
           "    QML_FILES"]
    cm += [f"        {f}" for f in files]
    cm.append(")")
    with open(os.path.join(folder, "CMakeLists.txt"), "w") as fh:
        fh.write("\n".join(cm) + "\n")
    return len(files)


def image_list(sub, predicate=lambda f: True):
    base = os.path.join(ROOT, "assets", sub)
    found = []
    for folder, _, files in os.walk(base):
        rel = os.path.relpath(folder, base)
        for f in files:
            if f.endswith(".png") and predicate(f):
                found.append(f"assets/{sub}/{f}" if rel == "." else f"assets/{sub}/{rel}/{f}")
    return sorted(found, key=lambda p: [int(t) if t.isdigit() else t for t in p.split("/")])


def block(files):
    return ",\n".join(f'            "{f}"' for f in files)


def write_main_project():
    #  No ImageFiles here. Each module declares the images its own QML names,
    #  and declaring them again at the root puts every one in two resource
    #  sets: qulrcc then emits the root's copy as a file-local buffer and the
    #  handle the module links against is never written. Main.qml names none.
    fonts = [f"assets/fonts/{f}" for f in sorted(os.listdir(os.path.join(ROOT, "assets", "fonts"))) if f.endswith(".ttf")]
    text = f"""import QmlProject 1.3

// Generated by tools/sync_project_files.py.
Project {{
    mainFile: "qml/Main.qml"
    qtForMCUs: true
    projectRootPath: "."

    MCU.Config {{
        fontEngine: "Static"
        defaultFontFamily: "Inter"
        addDefaultFonts: false
        autoGenerateGlyphs: true
        Experimental.mergeStaticTextGlyphs: true

        //  Compressed resources are decompressed into this cache at runtime,
        //  so it has to exist and hold at least the biggest single image: the
        //  full-width layers are 1280 x 480 Alpha8, 600 KB each. 21 MB holds
        //  every declared image at once, which is what the uncompressed build
        //  would keep in RAM anyway, so nothing is evicted mid-frame. The
        //  second entry covers the board's default allocation type as well
        //  as type 1.
        maxResourceCacheSize: [
            [22020096, 1],
            [22020096]
        ]
    }}

    QmlFiles {{
        files: [
            "qml/Main.qml"
        ]
    }}

    ModuleFiles {{
        files: [
            "qml/backend/backend.qmlproject",
            "qml/core/core.qmlproject",
            "qml/components/components.qmlproject",
            "qml/screens/screens.qmlproject"
        ]
        MCU.qulModules: ["Shapes"]
    }}

    FontFiles {{
        files: [
{block(fonts)}
        ]
    }}
}}
"""
    with open(os.path.join(ROOT, "EVBikes.qmlproject"), "w") as fh:
        fh.write(text)
    return len(fonts)


def main():
    for name, (uri, target, singletons, imports, qul_modules) in MODULES.items():
        print(name, write_module(name, uri, target, singletons, imports, qul_modules),
              "qml files")
    print("root project: %d font file(s), no images of its own" % write_main_project())


if __name__ == "__main__":
    main()
